### ISSUE TITLE
some extra callback needs

### ISSUE THREAD

**Issue by veboys** [Demigiant/dotween#10]
Hi, can you add some callbacks as below:
Tweener.OnPlayForwardStart()  called at the beginning of the PlayForward method.
Tweener.OnPlayForwardComplete() called when the PlayForward method is done.
Tweener.OnPlayBackwardsStart() called at the beginning of the PlayBackwards method.
Tweener.OnPlayBackwardsComplete() called when the PlayBackwards method is done.

thanks!

**Comment by Demigiant** [comment]
Hi,

I would prefer not to add those callbacks. The reason is that every callback I add will add 4B to every tween instance, while it's better to keep things as light as possible. In the meantime, consider that...

In place of `OnPlayForwardComplete` you can just use `OnComplete`
In place of `OnPlayBackwardsComplete` you can use `OnRewind`

Instead you would have to manage `OnPlayForward/BackwardStart` directly, but since those happen as a consequence of a direct script "order", that shouldn't be a problem.

**Comment by veboys** [comment]
thanks for your advice, I haven't think through early.

**Comment by Demigiant** [comment]
You're welcome :)
