### ISSUE TITLE
The referenced script on this Behaviour (Game Object '') is missing! in Version 3.4.0

### ISSUE THREAD

**Issue by cyliax** [Demigiant/dotween#103]
Hi,

I have an issue with version 3.4.0 in comparison to 3.1.0. I try to fade out a canvasgroup with:

`canvasGroup.DOFade(0f, speed);`

and I get that error. It happens on different canvasGroups either with OnComplete or without. If I'm going back to 3.1.0 everything looks fine. I can reproduce that every time.

>[Warning] The referenced script on this Behaviour (Game Object '<null>') is missing!
0. UnityEngine.Resources.Load()
1. DG.Tweening.DOTween.AutoInit()    D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:157
2. DG.Tweening.DOTween.InitCheck()    D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:951
3. DG.Tweening.DOTween.ApplyTo()    D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:959
4. DG.Tweening.DOTween.To()    D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:284
5. DG.Tweening.ShortcutExtensions46.DOFade()    D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween46/ShortcutExtensions46.cs:32
6. PanelPopup.Show()    Assets/Scripts/PanelPopup.cs:18
7. PanelPopupHelp.Show()    Assets/Scripts/PanelPopupHelp.cs:25
8. Panel.Show()    Assets/Scripts/Panel.cs:26
9. PanelLoading.Update()    Assets/Scripts/PanelLoading.cs:39

**Comment by Demigiant** [comment]
Hi!

That is very weird, and not related to CanvasGroups but to DOTween's initialization, and I have no similar issue here. Can you show me the method where you're creating the tween? Also, on what version are you? Also, did you check you don't have multiple versions of DOTween in the same project?

**Comment by cyliax** [comment]
Hi,

I have only one version of DOTween in my project at the same time. I was coming from 3.1.0 and then I deleted the entire DOTween folder in Demigiant and replaced it with the DOTween folder of my new downloaded archive of 3.4.0 and run the setup within your control panel. I'm using shortcuts only. Usually I stop old tweens with

`canvasGroup.DOKill();`

followed by

`canvasGroup.DOFade(0f, speed); // 0.4f in this example`

I'm on Unity 5.4.2f2 (macOS Sierra). 

I was disabling tweening on the first object with this error but then it stopped at my next canvasGroup. All other components and their properties seem to tween fine. And when I switch back to 3.1.0 there is no problem at all. And canvasGroup is not null, just to mention that.

**Comment by fmoyano** [comment]
Hi! I see this issue is a bit old, but I'm experiencing the same problem in version 1.2.335 (Unity version 2019.2.19f1). The editor console shows these two warnings when I start the game:

The referenced script on this Behaviour (Game Object '<null>') is missing!
UnityEngine.Resources:Load(String)
DG.Tweening.DOTween:AutoInit() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:174)
DG.Tweening.DOTween:InitCheck() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:1009)
DG.Tweening.DOTween:ApplyTo(DOGetter`1, DOSetter`1, Vector2, Single, ABSTweenPlugin`3) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:1017)
DG.Tweening.DOTween:To(DOGetter`1, DOSetter`1, Vector2, Single) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:378)
UIManager:HideButtons(Boolean) (at Assets/JellyGarden/Scripts/Metagame/UIManager.cs:239)
UIManager:HideAllUI() (at Assets/JellyGarden/Scripts/Metagame/UIManager.cs:331)
UIManager:StartUI() (at Assets/JellyGarden/Scripts/Metagame/UIManager.cs:155)
<InitTasksandUI>d__31:MoveNext() (at Assets/JellyGarden/Scripts/InitGame.cs:749)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
<StartGame>d__29:MoveNext() (at Assets/JellyGarden/Scripts/InitGame.cs:432)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
InitGame:Start() (at Assets/JellyGarden/Scripts/InitGame.cs:73)

And also this:

The referenced script (Unknown) on this Behaviour is missing!
UnityEngine.Resources:Load(String)
DG.Tweening.DOTween:AutoInit() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:174)
DG.Tweening.DOTween:InitCheck() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:1009)
DG.Tweening.DOTween:ApplyTo(DOGetter`1, DOSetter`1, Vector2, Single, ABSTweenPlugin`3) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:1017)
DG.Tweening.DOTween:To(DOGetter`1, DOSetter`1, Vector2, Single) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/DOTween.cs:378)
UIManager:HideButtons(Boolean) (at Assets/JellyGarden/Scripts/Metagame/UIManager.cs:239)
UIManager:HideAllUI() (at Assets/JellyGarden/Scripts/Metagame/UIManager.cs:331)
UIManager:StartUI() (at Assets/JellyGarden/Scripts/Metagame/UIManager.cs:155)
<InitTasksandUI>d__31:MoveNext() (at Assets/JellyGarden/Scripts/InitGame.cs:749)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
<StartGame>d__29:MoveNext() (at Assets/JellyGarden/Scripts/InitGame.cs:432)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
InitGame:Start() (at Assets/JellyGarden/Scripts/InitGame.cs:73)

The line of code to which these warnings refer is this:
`DOTween.To(() => playRectTransform.anchoredPosition, x => playRectTransform.anchoredPosition = x, finalAnchoredPositionPlay, 1);
`
However, everything seems to be working fine, at least in the editor. Do you think this could be problematic? What could be the cause?

**Comment by Demigiant** [comment]
Ahoy! Uhmmm that seems to be a problem loading DOTween's settings (the ones you set in the Utility Panel's Preferences). Where did you set their location (you can set it in the Preferences)? And is it possible that you deleted them from that location? Or that you never ran DOTween's Setup?

**Comment by fmoyano** [comment]
Ok, I think the DOTweenSettings might be the problem. I've just found out that I have two DOTweenSettings files, one in Assets/Resources and another one in Assets/.../Resources. The Preferences panel points to the former. I guess this must have happened during some update. The one in Assets/Resources seems to be fine, however the one in Assets/.../Resources is missing a script and shows a warning. Should I simply remove the latter, apparently problematic file?

**Comment by Demigiant** [comment]
Remove the latter and it will be solved, yes :)
