### ISSUE TITLE
Looping sequence can not be paused or killed

### ISSUE THREAD

**Issue by jeremedia** [Demigiant/dotween#105]
**Example:**
```
Sequence sequence = DOTween.Sequence();
sequence.Append( transform.DORotate(new Vector3(0,45f,0), 1f ).SetEase(Ease.InOutCubic) );
sequence.AppendInterval(2f);
sequence.SetLoops(-1, LoopType.Incremental);
sequence.SetRelative(true);
```
**Later:**
```
sequence.Pause();
```
or
```
sequence.Kill(true);
```
**Result:**
Object continues to rotate by 45 degrees every 1 second.

**Attempts at resolution:**

- Updated my pro installation to the 140 version with no change in this behavior.
- Tried non-infinite looping amounts
- Tried DOTween.PauseAll();
- Tried DOTween.Pause(transform);

**Comment by Demigiant** [comment]
Hi,

I made a test replicating your code and everything worked correctly here. I just made one change: you define the "sequence" variable inside a method it appears, instead of having it as a class variable. Maybe you're really doing that in your code, and thus your variable "sequence" exists only inside the method where you create it, and that's why you can't kill/pause it?

Cheers,
Daniele

**Comment by jeremedia** [comment]
Yes, assigning the sequence object to a local variable overriding the intended class variable was indeed the source of the problem. My apologies. 

What I still don't understand about C#, or perhaps Unity's implementation of C#, is why calling the pause method on the uninitialized sequence variable doesn't cause an exception.

**Comment by Demigiant** [comment]
There's no exception when killing/pausing a NULL sequence by design, because DOTween's logic uses extension methods to make everything lighter, and to allow writing `myTween.Kill()` without having to check if the tween is NULL or not first.

**Comment by Demigiant** [comment]
(in short, it's not a C# thing, but a specific DOTween's architectural choice)
