### ISSUE TITLE
DOShakePosition is not working with RectTransform

### ISSUE THREAD

**Issue by sivri** [Demigiant/dotween#11]
DOShakeScale and DOShakeRotation works but DOShakePosition is not working with RectTransform

**Comment by Demigiant** [comment]
I just checked to be sure, and it does work, but you have to consider that the default shake unit strength will be almost imperceptible with UGUI elements (because a 3D unit is very different from a 2D unit). Try to set the strength to 100 and it will be way more visible.

That said, I just updated DOTween with a RectTransform.DOShakeAnchorPos, which is much more performant with RectTransform elements, and has a default strength of 100. Grab it [here](http://dotween.demigiant.com/tmp/DOTween_1_0_615.zip).
