### ISSUE TITLE
Feature Request: option to complete previous tween if new one started on same component&tween

### ISSUE THREAD

**Issue by AdamNashGames** [Demigiant/dotween#118]
Let's say you have an object that shakes the screen with a DOShakePosition on the camera's transform every time it collides.  If you collide mid-shake, you will start a new tween, which appears to mark its starting point (and thus finishing point) as the position at which it started, which is a random position from the shaking.   To ensure this doesn't happen, I end up creating a Tween field in my script to save the tween, and then follow a pattern like this: 

if (screenShakeTween != null && screenShakeTween.IsPlaying())
    screenShakeTween.Complete();
screenShakeTween = Camera.main.transform.DOShakePosition(0.5f, 0.5f);`

Not that it's a big deal, but it'd be nice (if it's even possible) to be able to have a tween Complete() itself if a new one is started on the same component using the same tween.  

Just a thought =)  Keep up the awesome work on this amazing tween engine!

**Comment by Demigiant** [comment]
Hi Adam,

What you're talking about is called a kind of overwrite manager. I did implement one in my previous Unity tween engine, but I chose to avoid it this time. True, it's nice to have, but the real problem is that the only way to implement it is reflection, and reflection is very bad instead.

Cheers, and thanks for the nice words :)
Daniele
