### ISSUE TITLE
Tool to convert Animation and Path components to script

### ISSUE THREAD

**Issue by Naphier** [Demigiant/dotween#12]
The Animation and Path components are awesome, but (as would be expected) don't provide the full functionality of scripting a sequence. It would be AWESOME if there was a "convert to script" button that simply made a text file of the sequence for the animation/path. That way we could set up the path very quickly in the editor and then tweak it in script.

Thank you for your work on this. It has been one of the best & most time saving plugins I've bought!

**Comment by Demigiant** [comment]
Hey,

Thank you for the nice words, and thank you for getting DOTween Pro.

I initially pondered the idea of making a "convert to script" system (actually, more than a "convert to script", simply an Inspector which would modify its Component's script automatically). I decided not to though, because imho a Visual Editor is more useful if you can change the properties quickly and try it out. If it modified a script instead, it would have to recompile each time, and since Unity recompiles the whole project when a single script changes, in case of projects with lots of code it would become a bore having to wait all that time. Also, I believe that the pure script features of DOTween are simple enough that, if you want to work via code, it's easier to just create the code yourself.

Let me know what you think of this.

Cheers,
Daniele

**Comment by Naphier** [comment]
​You're right, it's probably easiest to simply script myself and have full
control from the start. I just like the speed of editing the waypoints.
Maybe I'll write a basic tool that just grabs the wp locations for me and
puts them into a text file.​

## 

---

Sean Mann          NaplandGames.com http://naplandgames.com/

## facebook.com/NaplandGames

**Comment by Demigiant** [comment]
Mhmm wait, thinking of it, I could easily add a button on DOTweenPath to "copy to clipboard" an array with all the current waypoints. What you think of this?

**Comment by Naphier** [comment]
​I think that would do it for me!
Thanks for listening and helping!​

**Comment by Demigiant** [comment]
Great, will do that tomorrow then :)

**Comment by Demigiant** [comment]
[Here you go](http://forum.demigiant.com/index.php?topic=33.0) :)

**Comment by Naphier** [comment]
Thanks, but your link goes to your forum which tells me this:
 An Error Has Occurred!
 The topic or board you are looking for appears to be either missing or off
limits to you.

On Wed, May 6, 2015 at 8:48 AM, Daniele Giardini notifications@github.com
wrote:

> Here you go http://forum.demigiant.com/index.php?topic=33.0 :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Demigiant/dotween/issues/12#issuecomment-99437702.

## 

---

Sean Mann          NaplandGames.com http://naplandgames.com/

## facebook.com/NaplandGames

**Comment by Demigiant** [comment]
Oh I thought you were registered already: that's where I place the latest versions of DOTween Pro (because the Asset Store is superslow to update). Register on the forum then follow the instructions [here](http://forum.demigiant.com/index.php?topic=2.0), so I can activate the private DOTween Pro area for you.

**Comment by Naphier** [comment]
I registered. User name is sean_mann, email: naplandgames@gmail.
Thanks!

On Wed, May 6, 2015 at 4:21 PM, Daniele Giardini notifications@github.com
wrote:

> Oh I thought you were registered already: that's where I place the latest
> versions of DOTween Pro (because the Asset Store is superslow to update).
> Register on the forum then follow the instructions here
> http://forum.demigiant.com/index.php?topic=2.0, so I can activate the
> private DOTween Pro area for you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Demigiant/dotween/issues/12#issuecomment-99594353.

## 

---

Sean Mann          NaplandGames.com http://naplandgames.com/

## facebook.com/NaplandGames

**Comment by Demigiant** [comment]
Hey, sorry for being a bother, but please follow the full instructions on that page I linked (by requesting group membership and sending me your invoice), so I can accept the membership request and activate the full account :)

**Comment by Demigiant** [comment]
Hey, I managed to activate your DOTween Pro membership on the forum. I'm writing you here too because I'm not sure my private message reply was sent (I'm rather new to having a private forum).
