### ISSUE TITLE
defaultTimeScaleIndependent issues with being set.

### ISSUE THREAD

**Issue by thekill473** [Demigiant/dotween#120]
Hey, thanks for reading.

When setting defaultTimeScaleIndependent to true in an Awake or Start function at the start of the game, it will flip back to false. 

Also setting it just before calling a DoMove tween. 
- The first time it won't do anything.
- The second time the tween will flip to the end.
- The third time it won't do anything.
- And after that it will work perfectly.

**Comment by thekill473** [comment]
Here's my code:
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

using DG.Tweening;

public class CameraController : MonoBehaviour
{
    #region Fields

    // SETTINGS //
    public float puzzleScreenYPosition;
    public float townScreenYPosition;
    public float transitionDuration;

    #endregion

    #region Unity Functions

    private void Awake()
    {
        //DOTween.defaultTimeScaleIndependent = true;
    }

    #endregion

    #region Functions

    public void SwapScreen(bool _puzzleScreen)
    {
        Debug.Log(DOTween.defaultTimeScaleIndependent);
        if (_puzzleScreen)
        {
            DOTween.defaultTimeScaleIndependent = true;
            transform.DOMoveY(puzzleScreenYPosition, transitionDuration);
        }
        else
        {
            DOTween.defaultTimeScaleIndependent = true;
            transform.DOMoveY(townScreenYPosition, transitionDuration);
        }
    }

    #endregion
}
```

**Comment by Demigiant** [comment]
Ahoy!

If you set the global timeScaleIndependent value before calling DOTween.Init manually or before your very first tween (which will call DOTween.Init if you didn't), it will be reset by the value you set in DOTween's Utility Panel. If you want to set it globally, either use the Utility Panel or call DOTween.Init first. Otherwise, you can set it for a specific tween at any time, by chaining a SetUpdate(true) to it.

Cheers,
Daniele
