### ISSUE TITLE
Short animations are skipped at beginning of a Sequence

### ISSUE THREAD

**Issue by wizcas** [Demigiant/dotween#147]
I found that there might be a problem of playing short tweens at the beginning of a `Sequence`. My code is like: 

``` csharp
public Tween Play (TweenCallback onStart, TweenCallback onComplete)
{
    return DOTween.Sequence()
        .OnStart(() => {
            if (onStart != null)
                onStart();
            // ...
        })
        // step 1
        .Append(_flyRect.DOScale(Vector3.one, popDuration).SetEase(popEase))
        // step 2
        .Join(target.DOFade(popEndAlpha, popDuration))
        // step 3
        .Append(_flyRect.DOAnchorPos(toPos, flyDuration).SetEase(flyEase))
        .Join(_flyRect.DOScale(flyEndScale, flyDuration))
        .Join(target.DOFade(flyEndAlpha, flyDuration))
        .OnComplete(() => {
            if (onComplete != null)
                onComplete();
        });
}
```

I set the `popDuration` as `0.2 secs`, and when I call the `Play()` method, the whole animation looks like playing from **step 3** directly. 

If the `popDuration` is increased to `1 sec`, I can see the **step 1** and **step 2**.

So I added a few `AppendCallback()`s between appended tweens, trying to figure out the time where each tween began to play. The result was weird - **step 1** and **step 2** didn't take any time to play if I set the `popDuration` smaller than 0.3 seconds. 

**I had to add a `AppendInterval (.3f)` at the beginning of the `Sequence` in order to make the whole animation right.**

Is this a bug or I made some mistake? Please help, thanks!

**Comment by Demigiant** [comment]
Hi!

I use durations lower than 0.3" a lot, plus I never heard this issue, so I'm quite confident that there should be no bugs there.

Am I right in thinking that you're testing this from inside Unity's editor, and the Sequence starts immediately when the game starts? When you press play inside the Editor, Unity hiccups for the first part of a second (even more, depending on the machine), and thus when the tween finally updates 0.3" might have passed, and that's why you get the impression the first part was skipped (meaning it was played instantly). This hiccup doesn't happen in builds, but in general it's better not to trust Unity with any animation/movement/effect for the first couple seconds after it loads.

If what I wrote is not your case, then there's probably something else causing a hiccup in the same moment you create and start the tween.

Let me know, and cheers,
Daniele

**Comment by wizcas** [comment]
Hi Daniele,

Thanks for your reply! The Sequence is not started as soon as the game starts. It's triggered through Component's context menu. I'm  aware that the editor hangs up when context menu popped out. Perhaps hiding a context menu and waking up the editor causes the hiccup you mentioned as well?

**Comment by Demigiant** [comment]
Ah, that could definitely be the reason for it.
By the way, if you set DOTween to use smoothDeltaTime from DOTween's Utility Panel, that *might* help.

**Comment by wizcas** [comment]
I'll give it a try. Thanks so much
