### ISSUE TITLE
Redundant log error warning when using lambdas for callback with parameters

### ISSUE THREAD

**Issue by optimisez** [Demigiant/dotween#162]
It logs a lot of warning that is not necessary.

![image](https://user-images.githubusercontent.com/7009368/31676819-6187c55a-b39b-11e7-963e-682ad0ae053d.png)

**Comment by Demigiant** [comment]
Hi,

Those are kind of necessary I'd say, because even if DOTween captures those errors and doesn't crash your project, it's still a warning that there's faulty code in your callback which you should fix. If you don't want to see them though, you can change the Log Behaviour in DOTween's Utility Panel to "Errors Only" ;)

P.S. The error is not happening because you're using lambdas, but because the code you put inside it is trying to do something that Unity is not allowing (like adding a Component to a disabled gameObject).
