### ISSUE TITLE
Doesn't work with runtime version 'Experimental(.NET 4.6)'

### ISSUE THREAD

**Issue by Dosukkoi** [Demigiant/dotween#184]
In PlayerSettings -> Other Settings -> Configuration -> Scripting Runtime Version

If version was .NET 3.5, it works perfect.
but when version was .NET 4.6, DOTween works strangely.

For example, DOJump, if end value was (2.0f, 2.0f. 0),
DOJump works wrong end value, like (2.0f, 1.1f, 0)
Other functions were same.

In conclusion, please support .NET 4.6

**Comment by Demigiant** [comment]
Hi,

I'm going to try with DOJump in the next days, but that seems very weird. Are you using the hyper-compatible version by any chance? That might have issues with .NET 4.6 (if Unity has issues with it), but otherwise there should be nothing wrong there. Did you check also that your end values are set correctly, and that the tween is not simply interrupted by something else?

Cheers,
Daniele

**Comment by Dosukkoi** [comment]
I changed just .NET version 3.5 to 4.6.
I checked value before the DOMove line, but end value was correct...

**Comment by Demigiant** [comment]
Ahoy!

Got it! It was the order of operations which DOJump did in a specific way compared to the rest, and wasn't reflected in the same way on .NET 4.6. [Here's the new version](http://dotween.demigiant.com/download.php) with the fix :)
