### ISSUE TITLE
The newest ver of unity imported DOTween cause display problem

### ISSUE THREAD

**Issue by woodtemp** [Demigiant/dotween#195]
Excuse me,my English is not good.

OS Ver:Win7(x64)
Unity Ver:5.6.5,2017.2.2,2017.3.1,2017.4.1(This vers are all released in the last half year)
DOTween Ver:1.1.640,1.1.695

Steps:
1.Create a new 2D project
2.Add a UI->Text(as the picture below)
3.Import DOTween
4.Use mouse's left click follow the red arrows 1st 2nd 3rd,and then the text "New Text" will disappear.(**Attention**:The 2nd red arrow is point to Win7's taskbar)
![aaa](https://user-images.githubusercontent.com/38200480/38537611-252a5982-3cc2-11e8-8862-5b153eb9c76e.jpg)

**Comment by Demigiant** [comment]
Hi,

This is a bug with Unity 5.x (don't remember which minor version started it), which happens if there's any DLL in the project, and also rather randomly (happened also with older versions of DOTween and other plugins). The text will reappear if you deactivate/reactivate it or enter play mode, which is a nuisance I know, but it should be solved in Unity 2017.

**Comment by woodtemp** [comment]
Thank you for reply!
I got it,I'll wait Unity 2018.
(2017 did't solved it.I found this bug in 2017.3.1 and 2017.4.1,but the older ver like 2017.2.0 is normal.)

**Comment by Demigiant** [comment]
Agh, it comes and goes :|
