### ISSUE TITLE
DOTweenPath reset and play?

### ISSUE THREAD

**Issue by sommerper** [Demigiant/dotween#210]
I created a DotweenPath in the unity editor and refenced it in a c# script.

How can I play the tween multiple times?

`myPath.DOPlay();` does trigger it once but then it's stuck at it's endpoint.

`myPath.DORestart();` and `myPath.DOGoto(0f);` do nothing when called.

**Comment by Demigiant** [comment]
Hi,

DORestart and DOGoto are the way to go (DOPlay just continues from the last playing position, so if the path is already complete or running nothing will happen). But it will work only if you disable autoKill, otherwise as soon as the tween is complete it will be destroyed to free up memory.

Cheers,
Daniele
