### ISSUE TITLE
Looped Tweens are not killed if GameObject disabled?

### ISSUE THREAD

**Issue by jmp909** [Demigiant/dotween#219]
Looped Tweens are not killed if the MonoBehaviour/GameObject creating the tweens is disabled (since the tweens exist on the Static DOTween?)

what would be the expected behaviour here?

for safety i'm killing my Tween `OnDisable`

is this a case of depending on what the user wants to happen when the game object / script is disabled?
Personally i'd expect tweens should no longer continue running .

thanks
J

**Comment by Demigiant** [comment]
Tweens are not tied to gameObjects (also because they can run on many other types of objects): they use a higher abstraction layer, so it's up to you to disable tweens if they are working on a gameObject and said gameObject gets disabled. There is a safe-mode which uses a try-catch to prevent running tweens encountering errors if their target is destroyed (which, for example, in case of Transforms would mean in case their gameObject is destroyed), but that's all.
