### ISSUE TITLE
Calculating tween duration in runtime

### ISSUE THREAD

**Issue by Cardinal90** [Demigiant/dotween#223]
Let's say I want to tween a transform's position with some known speed, but I don't know its `from` and `to` positions in advance. To achieve this I calculate the distance and divide by speed to get duration. That's fine.

But what if this tween is not the first in sequence. When it starts, the transform's position may have changed. But as the tween was created before the whole sequence even started, its duration was calculated using the wrong position.

The only way I see to get the correct duration is to start a new sequence in an `OnComplete` callback, but that's kinda hacky and defeats the purpose of sequences.

Is there any way to do it better? I'm tempted to suggest a feature - let the duration parameter accept a getter. Doesn't seem like an easy thing to implement though.

**Comment by Demigiant** [comment]
Hi,

When not in Sequences, you could use [SetSpeedBased](http://dotween.demigiant.com/documentation.php?api=SetSpeedBased) instead of calculating the duration yourself, but when in Sequences its a completely different matter, since that won't work. Using OnComplete would be a solution indeed, but in theory in most cases you should already be able to know and calculate the start and end position of an object inside a Sequence, and assign the corresponding evaluated duration.

As a secondary note, for nicer "writing", maybe you could also use a coroutine in this case, with a series of tweens that use `yield return myTween.WaitForCompletion()` to wait for each one to finish and then create/start the next SetSpeedBased one.

P.S. accepting a duration getter wouldn't be a solution here anyway, because a Sequence needs to calculate its exact duration before it starts.

**Comment by Cardinal90** [comment]
Thank you!
