### ISSUE TITLE
Unable to attach text animation to TMPro text

### ISSUE THREAD

**Issue by vipin8169** [Demigiant/dotween#237]
When I try to attach a text animation to the TMPro text (in the pro version), it says that no valid component was found for the animation. Could you please help me with this?

![image](https://user-images.githubusercontent.com/4578304/43359787-e55e68d8-925d-11e8-9e9d-4a3fb11e786d.png)

Also, how do I use `GetComponent<DOTweenAnimation>()` if there are multiple animation components of different type (say text and move) are attached to the same gameobject?

**Comment by Demigiant** [comment]
Hi,

The problem you're having with TextMesh Pro can be caused by 2 issues:

1. You didn't import/reimport DOTween Pro and run the Setup after installing TextMesh Pro. You can access the Setup from DOTween's Utility panel (inside the "Tools > Demigiant" menu).

2. You're on Unity 2018.2, where there's a new version of TextMesh Pro that is different from the previous ones and can't be recognized by DOTween. I am doing the final tests on a new upgrade that will fix this, but in the meantime you can fix it manually by following [these instructions](http://dotween.demigiant.com/support.php?faq=TextMesh%20Pro).

About GetComponent and DOTweenAnimations, you can use GetComponents instead, which will return a top-down list of all DOTweenAnimations on a gameObject. Or you can access the tweens directly by giving them an ID and using DOTween's static commands (you can pass an ID to DOTween.Play/Restart/etc).

Cheers,
Daniele

**Comment by vipin8169** [comment]
Thank you @Demigiant  for your response. 
I am using 2018.1, thankfully :)
Something weird happened, i was able to use TMPro with DOTween animantion component, but then I don't know I loaded a different scene or applied the values to prefab and all of a sudden i got this error saying DOTtween couldn't find text component. So, I had to redo everything and it worked again.
Could you please help me with this as well>> https://stackoverflow.com/questions/51574914/dotween-change-endvaluestring-for-tween-animations-at-runtime

PS: The text animation is really great, i wish I could resolve all the issues so that I can use it properly.

**Comment by Demigiant** [comment]
Answered :)

**Comment by vipin8169** [comment]
Much thanks!

**Comment by Demigiant** [comment]
A pleasure! :)

**Comment by iLyxa3D** [comment]
>TextMesh Pro not recognized on Unity 2018.2
> Within the next week a fix will be up on the Asset Store, but in the meantime you can add it manually by following these steps:
>1) reimport DOTween Pro
>2) rename the "DOTweenTextMeshPro.cs.addon" file to "DOTweenTextMeshPro_mod.cs" BEFORE running the setup
>3) add a "DOTWEEN_TMP" define to Unity (in the Project Settings Panel, under "Other Settings > Scripting Define Symbols")

This was useful for me.

**Comment by hheimbuerger** [comment]
Had the same issue, and I simply had forgotten to select the "TextMesh Pro" option in the DOTween Utility Panel.

![image](https://user-images.githubusercontent.com/159414/199353812-73f57366-7d0d-46f1-abd1-8f6349017029.png)

Enabled that, "Apply", and the "No valid component" error disappeared!

**Comment by maxmason007** [comment]
Hey @Demigiant. I just downloaded and have the latest version 1.2.745 running unity 2021.3.11f1 and I tried to fade a TextMesh Pro object and its given me the 'No valid component error'. 

I have updated the modules to include TextMeshPro but it gives me this error. Any thoughts? 


![Snip20230830_2](https://github.com/Demigiant/dotween/assets/105564077/4baab30e-92d1-47ec-a709-37d5a8302323)

**Comment by Demigiant** [comment]
Ahoy! Just answered on the other thread. Let me know :)
