### ISSUE TITLE
Target mode doesn't work with 2D items

### ISSUE THREAD

**Issue by vabric** [Demigiant/dotween#24]
Hi,
I'm starting to use the new feature you added on monday, and I think there's a problem with UI objects. With 3D objects it works great, but when using an object attached to a RectTransform as target, the tween doesn't move to the wanted position.
Thanks

**Comment by Demigiant** [comment]
Hello,

I realized what the problem is, but I'm not sure how to deal with it. Right now I'm taking the transform.position of the target for coordinates. That works with 3D/2D objects, but not with UGUI elements, because those are animated using rectTransform.anchoredPosition.

Now, I could simply take the rectTransform.anchoredPosition value of a target, in case we're using UGUI elements, but that wouldn't work correctly unless both the target and the animated object have the same anchor center (pivot) and anchor offsets.

Thinking about it...

**Comment by vabric** [comment]
Hi,

After testing a little more, it seems that the object moves to the center of the screen instead of moving towards the target UI object.
It's strange that it can not work with UGUI elements. I already used the MoveTo tween on UI elements before, using transform.position as target, and it worked well (unless, as you said, the anchor is not in the center of the object).

If you try this component with 2 UI objects, it will work :

```
using UnityEngine;
using System.Collections;
using DG.Tweening;

public class MoveTo : MonoBehaviour
{
    [SerializeField] private GameObject _target = null;

    protected void Start()
    {
        transform.DOMove(_target.transform.position, 0.5f);
    }
}
```

**Comment by Demigiant** [comment]
If you use transform.DOMove and a transform.position as a target it will work indeed, but moving the transform of a UGUI element is highly un-recommended, because Unity would need to update tons of variables and that would be an intensive operation executed every frame (and it wouldn't re-adapt in case the screen size changes).

That's why I automatically use rectTransform.anchoredPosition with a UGUI DOTweenAnimation, which is the right way to do it but creates issues with the new target field (I'm trying to understand how to convert one anchoredPosition to another, but it's pretty crazy).

The equivalent would be:

```
((RectTransform)transform).DOAnchoredPos(((RectTransform)_target.transform).anchoredPosition, 0.5f);
```

**Comment by vabric** [comment]
I tried converting the target position using RectTransformUtility.ScreenPointToLocalPointInRectangle(). Normally, it should result in a position relative to the local RectTransform but I can't make it work correctly.

**Comment by Demigiant** [comment]
I've been wrapping my head around it all day (between other jobs) and I still didn't find the right way to convert one achoredPosition to another (also considering that eventual RectTransform parents should be taken in consideration) :/

**Comment by Demigiant** [comment]
P.S. Just opened a thread [here](http://forum.unity3d.com/threads/find-anchoredposition-of-a-recttransform-relative-to-another-recttransform.330560/).

**Comment by Demigiant** [comment]
Still didn't find a way, sigh. I'm gonna try some more, but otherwise I will have to show a warning that will tell users that it works only with GUI elements with the same anchor/pivot.

**Comment by vabric** [comment]
I think there's something missing in Unity for doing what we want, or something is broken, because as I understand [this doc](http://docs.unity3d.com/ScriptReference/RectTransformUtility.ScreenPointToLocalPointInRectangle.html), this should help us.
Anyway, showing a warning regarding the anchor and pivot seems to be a good compromise for now. It's a little constraining, but it'll save us a lot of time :).

**Comment by Demigiant** [comment]
Yup, I tried that method too, but it returns completely wrong results for no apparent reason. Also, while working on this, I discovered that there's lots of public RectTransform and RectTransformUtility methods that are not even documented :(

I'm gonna insist for today too, but otherwise I'll give up and use the warning method (which I actually already implemented, but I'd like to make this work).

**Comment by Demigiant** [comment]
I might've made it! After writing the last message I was annoyed and made a weird "f**k you RectTransform" test, and suddenly things started working! Back to you in a short while, if I make this work for real ;)

**Comment by Demigiant** [comment]
Ok got it for real! Now I have to solve what happens if the pivot is not 0.5x0.5 and then it might be done. Wheeeeeeeeeeew!

**Comment by vabric** [comment]
Oh, nice :). I'm curious about how you did it ^^.
Great news anyway!

**Comment by Demigiant** [comment]
Here it is, I made a handy method so I won't ever have to do it again :)

By the way, WorldToScreenPoint asks for a camera in case of Camera ScreenSpace Camera, but apparently it doesn't really care so passing NULL works in all cases. I'll have to investigate more.

```
/// <summary>
/// Converts the anchoredPosition of the first RectTransform to the second RectTransform,
/// taking into consideration offset, anchors and pivot, and returns the new anchoredPosition
/// </summary>
public static Vector2 SwitchToRectTransform(RectTransform from, RectTransform to)
{
    Vector2 localPoint;
    Vector2 fromPivotDerivedOffset = new Vector2(from.rect.width * 0.5f + from.rect.xMin, from.rect.height * 0.5f + from.rect.yMin);
    Vector2 screenP = RectTransformUtility.WorldToScreenPoint(null, from.position);
    screenP += fromPivotDerivedOffset;
    RectTransformUtility.ScreenPointToLocalPointInRectangle(to, screenP, null, out localPoint);
    Vector2 pivotDerivedOffset = new Vector2(to.rect.width * 0.5f + to.rect.xMin, to.rect.height * 0.5f + to.rect.yMin);
    return to.anchoredPosition + localPoint - pivotDerivedOffset;
}
```

But now there is another terrible problem. In order to convert one anchoredPosition to another, the RectTransforms need to be fully initialized. And they are not yet initialized inside awake calls, which is where DOTween needs to create all tweens :(

**Comment by vabric** [comment]
I think that it's like the other functions : if your canvas is set in overlay mode, you have to pass a null camera.

You could convert the anchoredPosition to one another when the tween start playing.

**Comment by Demigiant** [comment]
Nope: passing NULL even if the canvas is in Screenspace Camera works. I assume it takes automatically the main camera, but I'll investigate more. Especially because I didn't find a way to get the Canvas associated with a RectTransform (other than traversing the hierarchy upwards, which seems silly).

I can't convert the anchoredPosition when the tween starts playing, because the tween needs it before playing, when it's setup. I won't be able to work more on this today, but this evening and tomorrow I'll be back on it, to hopefully find some sneaky solution.

**Comment by Decavoid** [comment]
How to get Canvas:

```
    gameObject.GetComponentsInParent(true, list);
    if (list.Count > 0)
        m_Canvas = list[0];
```

From Unity UI source: https://bitbucket.org/Unity-Technologies/ui/src/87c9a350fbecd8336df86563688a9bbe60945ea7/UnityEngine.UI/UI/Core/Graphic.cs?at=4.6#cl-169

**Comment by Demigiant** [comment]
Took me a while  (sorry for that), but I finally decided to use Start instead of Awake when creating a tween with a UGUI target. [Here is the update](http://forum.demigiant.com/index.php?topic=80.new#new) :)
