### ISSUE TITLE
Allow adding DOTweenComponent manually

### ISSUE THREAD

**Issue by odysoftware** [Demigiant/dotween#240]
Hey there, just started using dotween and i am liking it so far - now I wonder if there is a way to avoid it using DontDestroyOnLoad feature of unity. This feature has been depreciated 1 and 1/2 year ago. My game is using additive scene loading, so I want to put the dotween script into my manager scene. but can't since its auto assigning itself as dontdestroyonload. I was looking if there is a way to manually put the dotscreen script in the scene manager - but its not available as a compoonent script.

So how could this be done?

Thanks,
Oliver

**Comment by Demigiant** [comment]
Hi Oliver,

DontDestroyOnLoad has never been deprecated afaik, but if you have more info let me know.

DOTween needs it so that its management component is created regardless of the starting scene and can work even during scene transitions, and it shouldn't be of any hindrance to your process (while it's very useful for regular non-additive usage).

Cheers,
Daniele

**Comment by odysoftware** [comment]
Yeah you are right its not deprecated but not recommended either :)

From Unity docs:
"It is recommended to avoid using DontDestroyOnLoad to persist manager GameObjects that you want to survive across scene loads. Instead, create a manager scene that has all your managers and use SceneManager.LoadScene(<path>, LoadSceneMode.Additive) and SceneManager.UnloadScene to manage your game progress." (http://docs.unity3d.com/Manual/MultiSceneEditing.html in Tips and Tricks)​

Due to this and when I started with my project I went this route without any dontdestroyonload objects - and from all the plugins in use - which need to be persistent - only dotween is forcing me to use dontdestroyonload. There is no way to add the script yourself to the manager scene...

I totally understand that it is necessary to run at all times as many other plugins do too but now having only one plugin/object running dontdestroyonload - which I really don't like to have - makes it unclean.

So it would be great if dotween would also give us the option to get manually added via a script and only if its not present do it like now (add automatically as dontdestroyonload) in order to keep compatibility and ease of use for people who don't have their own manager scene?

Thanks for listening,
Oliver

**Comment by Demigiant** [comment]
There's indeed better alternatives to DontDestroyOnLoad when using additive scenes, but for a general workflow that should work in any type of project it's not "not recommended" (and I assume you understand the pros/cons of the other plugins that don't use the same design choice) :P

That said, I understand the desire to have a runtime hierarchy the way one wants, so I added this to my todo list. Please consider that first I have a big modular upgrade planned (almost finished), and then another feature, so this might take a little while.

Cheers,
Daniele

**Comment by odysoftware** [comment]
Hey there,

sure I understand and I was hoping that maybe its not so hard to put the "manager code" from dotween into a script which you could also manually put in the scene.

But since I am a developer myself - I know depending on how the plugin is build it may or may not be easy to seperate this logic :)

And yeah... most people probably just love to have it magically work, doing auto pooling on its own etc. But I myself, always like to be in full control of the happenings - and thus I aways want to decide where to put a gameobject (at least the controller) and not seeing some stuff appearing out of nowhere :). 

So I think some option to make it work without creating itself automatically would really be a great addition.

Thanks again for your time and great work on the plugin!!

**Comment by Demigiant** [comment]
Thanks to you for the interesting chat :)

And by the way, about how it would work, my idea was that, before calling any tween, you would be able to create the DOTweenComponent manually and place it wherever you want. But via script at runtime, not by dragging it in the Hierarchy in edit mode. Though while writing this, I'm thinking I might indeed allow it in edit mode (might also help for a future feature I have in mind). Will ponder about it, but might go for the latter as you mentioned.

P.S. Shouldn't take much time, but I can't touch anything else in DOTween until I at least finish the modular update (since that's a really major architectural change).

**Comment by odysoftware** [comment]
Sounds great and yeah while creating it via script would be fine too - the latter version would make it "more streamlined" to the way most other plugins do it which require persistent gameobjects - at least that was my observation from the past year :)

And yeah I can totally understand that you have to finish up your current work - I guess it's never a good idea to touch core behaviours while you are already modifying something else.

Anyway thanks for consideration and can't wait to see it work.

**Comment by Demigiant** [comment]
Here you go: [v1.2.075](http://dotween.demigiant.com/tmp/DOTween_1_2_075.zip) :) You can now add the DOTween component manually to the Hierarchy via the GameObject menu (_Demigiant > DOTween Manager_).

Can you let me know if it's alright for you?

P.S. Please note that this update also includes the Modules upgrade, so [follow these instructions](http://dotween.demigiant.com/support.php#before-modules) carefully when upgrading because it's a major one (and **if you're using DOTween Pro instead let me know and don't test this**, because you'll first need the Pro upgrade).

**Comment by odysoftware** [comment]
Hey there,

just tried it - removed the old Dotween folder and just copied it in and used setup. Seems to work great - I added manually to my manager scene and renamed it so it fits my other objects - everything is still working as before (!!) :)

Thanks a lot for your efforts and hopefully some others can make use of this too.

Kind regards,
Olicver

**Comment by Demigiant** [comment]
Great :)
