### ISSUE TITLE
I would like to have keyboard control engaged for path transfer.

### ISSUE THREAD

**Issue by castanets** [Demigiant/dotween#260]
this is google Translate language. Sorry.

Hello DOTween producer.

I'm not using the Pro version yet. Perhaps my question is in the Pro version, but it's too early to judge.

 I'm currently trying to open a path movement related scene in the example project scene and write this and that. I'd like to finally get the object to move along its path and use the keyboard to move forward or backward through the path.
 Keyboard input is for simple testing, and I'll finally have the object repeat 'move' and 'stop' along the path.

this is possible?

i need help. little hint please.

**Comment by castanets** [comment]
now, anyway i dont care. i will use itween. dotween is dog shit.

**Comment by Demigiant** [comment]
> now, anyway i dont care. i will use itween. dotween is dog shit.

Oops, sorry I missed the first post (it can happen, I'm a single human being and sometimes I'm overcome by too many things). I normally would apologize but you clearly don't deserve that.

The answer would've been "yes, you can, like this...". Next time please remember that in this case you were asking support for a free product, so while I usually try to answer on time, if that doesn't happen maybe a little more patience (or a later ping) would be considered polite.

**Comment by castanets** [comment]
xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxx


this is my odernumber.

i want refund.

**Comment by castanets** [comment]
It doesn't provide the core functionality I want, or it's very inappropriate to use.

**Comment by castanets** [comment]
> > now, anyway i dont care. i will use itween. dotween is dog shit.
> 
> Oops, sorry I missed the first post (it can happen, I'm a single human being and sometimes I'm overcome by too many things). I normally would apologize but you clearly don't deserve that.
> 
> The answer would've been "yes, you can, like this...". Next time please remember that in this case you were asking support for a free product, so while I usually try to answer on time, if that doesn't happen maybe a little more patience (or a later ping) would be considered polite.

xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxx

this is my odernumber.

i want refund.

**Comment by Demigiant** [comment]
If you bought the Pro, write me a mail (via the mail button you can find [on this page](https://assetstore.unity.com/publishers/1341), just below my logo), and attach:

- your PDF invoice
- your order number (which I'll now erase from your posts because it shouldn't be shared publicly)

Also consider that, while I always issue refunds when asked, I have no obligation to do that and it's a personal choice (many asset developers never issue refunds), so you will want to be polite in your mail and say "please". I don't understand why you have to be so aggressive, dude, especially considering that a lot of people find DOTween very appropriate to use, so it might simply not be for your tastes, which may happen but doesn't mean you have to go on a rampage. Let me know your thoughts on this in the mail.
