### ISSUE TITLE
Module errors with Assembly Definitions

### ISSUE THREAD

**Issue by cfoulston** [Demigiant/dotween#261]
Hi, I'm using Assembly definitions in my project for all scripts. I noticed that after upgrading to v1.2.055 some extension methods cannot be found. This is because my asmdef's can't find the module scripts.

Solution is to add an asmdef: DOTween/Modules/DOTween.Modules.asmdef
This works. But will change the module scripts assembly from "Assembly-CSharp" to "DoTween.Modules". 

So far no problems. However, I'm not sure if you're using Reflection in DOTween? If so, this may fail if explicitly referencing the "Assembly-CSharp" assembly.

Might be worth including an asmdef for people that use them.

**Comment by Demigiant** [comment]
Hi,

I'm delaying this because I'm trying to think of a way that would allow libraries to access DOTween's lose script modules even on older Unity versions that don't have asmdef (but I'm mostly leaned towards the idea of using asmdef like you said). I will probably get full time on this issue at the end of October though.

**Comment by bdominguez** [comment]
Any news?

**Comment by Demigiant** [comment]
I'm implementing an option to create an asmdef when setting up the modules. But right now I'm stuck with trying to add Bezier paths to DOTween, so I'll get back to this when that is done.
