### ISSUE TITLE
Fixed Update Time wrong

### ISSUE THREAD

**Issue by cuinc** [Demigiant/dotween#263]
> while Sequence UpdateType is Fixed, the delta is not Time.fixedDeltaTime

` void FixedUpdate()
        {
            if (TweenManager.hasActiveFixedTweens && Time.timeScale > 0) {
                TweenManager.Update(UpdateType.Fixed, (DOTween.useSmoothDeltaTime ? Time.smoothDeltaTime : Time.deltaTime) * DOTween.timeScale, ((DOTween.useSmoothDeltaTime ? Time.smoothDeltaTime : Time.deltaTime) / Time.timeScale) * DOTween.timeScale);
            }
        }`

**Comment by Demigiant** [comment]
Sorry, forgot to reply sooner.

If you query `Time.deltaTime` inside a fixed timestep it will return `Time.fixedDeltaTime` (see [here](https://docs.unity3d.com/ScriptReference/Time-fixedDeltaTime.html), "For reading the delta time it is recommended to use Time.deltaTime instead because it automatically returns the right delta time if you are inside a FixedUpdate function or Update function").
