### ISSUE TITLE
DoTween Animation Color animation initializes to From color even if AutoPlay is disabled

### ISSUE THREAD

**Issue by thsbrown** [Demigiant/dotween#272]
![image](https://user-images.githubusercontent.com/2967721/49242568-f6387b80-f3bf-11e8-8176-85559e5cb0d9.png)

This is my current DoTween animation, when the game is started it always set's my Image component color to the "From" color despite AutoPlay being unselected.

Expected behavior:

Starts in default color and when playing animation it tween from the from color back to the default one.

Thanks in advance!

**Comment by Demigiant** [comment]
Hi,

FROM is designed to work and be used like that, because its purpose is to invert the animation and the state of its target from the very beginning (it's generally used with menu panels for example, where it's easier to keep them open while working, and have FROM close them at startup and open them when played).

If you want to jump to the set value and back when playing, you'll need to set it to TO and use code, so you can do this:
```
// Jump to the end and play backwards towards the beginning
myDOTweenAnimation.DOComplete();
myDOTweenAnimation.DOPlayBackwards();
```

Cheers,
Daniele
