### ISSUE TITLE
On iOS Tween works not Smoothly

### ISSUE THREAD

**Issue by Marshall-Hu** [Demigiant/dotween#283]
Unity 2018.2.14f1.

**Comment by Demigiant** [comment]
Hi,

This sounds very weird, DOTween is a lightweight engine which doesn't have any architectural difference between different OS. Can you explain me more? Also, are you sure it's not a problem of "what" is being tweened and not in the tweening engine (which in general is what changes)?

Cheers,
Daniele

**Comment by Marshall-Hu** [comment]
It works well in an old project with unity2017. I creat new project in unity 2018, with default scenes setting. Adding RawIamge in the screen, if I touch it ,it will smooth to the right of the screen(this action seems very simple).But It work in very low fps(lower than in the unityEditor). Code is here:
`    public void OnPointerClick(PointerEventData eventData)
    {
        gameObject.transform.DOMove(new Vector3(Screen.width * 1.5f, Screen.height * 0.5f, 1), 1.0f);
    }`

**Comment by Demigiant** [comment]
Ah, I think I know what's happening there. I can confirm 100% that the problem is not with DOTween, but with what Unity does in the background when you move a UI element, which apparently is now less efficient than before.
As an important suggestion, **never use DOMove with UI elements**. DOMove moves the transform of an object, but Unity doesn't like when you change a transform's position on Canvas elements, and does a lot of extra calculations each time that happens. Use [DOAnchorPos](http://dotween.demigiant.com/documentation.php?api=DOAnchorPos) with the RawImage's RectTransform instead (which uses Canvas coordinates).

**Comment by Marshall-Hu** [comment]
Thats help a lot. by the way 新年快乐

**Comment by sandeepsmartest** [comment]
> Ah, I think I know what's happening there. I can confirm 100% that the problem is not with DOTween, but with what Unity does in the background when you move a UI element, which apparently is now less efficient than before.
> As an important suggestion, **never use DOMove with UI elements**. DOMove moves the transform of an object, but Unity doesn't like when you change a transform's position on Canvas elements, and does a lot of extra calculations each time that happens. Use [DOAnchorPos](http://dotween.demigiant.com/documentation.php?api=DOAnchorPos) with the RawImage's RectTransform instead (which uses Canvas coordinates).

Hey first of all i would like to say great work for this Dotween library.Im using DoAnchorPos on ui element as you suggested but could still see a jittery movement.Below given is the snippet.Please point me in the right direction.Thanks in advance
` if (Input.GetKeyDown(KeyCode.Space))
        {
            Sequence s1 = DOTween.Sequence();
            SourceObj_Rect.DOAnchorPos(TargetObj_Rect.localPosition,1);
            s1.OnComplete(
                () =>
                {
                    Debug.Log("Oncomplete");
                }
            );
        }`

**Comment by sandeepsmartest** [comment]
And the version im using is 2018.3.3f1

**Comment by Marshall-Hu** [comment]
So，in the unity. It works well?




On 04/24/2019 18:25, sandeepsmartest wrote:

And the version im using is 2018.3.3f1

**Comment by sandeepsmartest** [comment]
im sorry it is not working proper in Unity and on iOS device aswell.Movement is jittery.Any suggestions??

**Comment by Marshall-Hu** [comment]
My situation works fine in the unity. And I solve it by adding Application.targetFrameRate = 60 .Hope it does work




On 04/24/2019 19:21, sandeepsmartest wrote:

im sorry it is not working proper in Unity and on iOS device aswell.Movement is jittery.Any suggestions??

**Comment by Demigiant** [comment]
Thanks for the nice words @sandeepsmartest, and thanks for the help @Marshall-Hu :)

@sandeepsmartest, maybe you're moving an object that has tons of children with layout elements etc? I would recommend to look for things that refresh when you move said UI elements, or other things happening in the background unrelated to that (you can use the Profiler and activate Deep Profiling to help). I can confirm that it's not a DOTween problem because all DOTween does is change the anchoredPos of the UI element every frame, which is an almost zero-impact operation.

**Comment by sandeepsmartest** [comment]
@Demigiant  Thanks for your immediate response.The ui element that im moving is not at all having children.And i tested this in empty scene where i hardly have 5 game objects(Including Camera and Light) in editor(mac).Same jittery movement is also being observed in iOS devices aswell.
I already profiled and i found nothing surprising.Will look into the "refresh" thing which you were suggesting.Please suggest me any other ways .Thank you @Demigiant 
@Marshall-Hu  thanks for your prompt response.i tried setting target FPS in editor(Mac) but no luck.

**Comment by nikomikulicic** [comment]
Hi guys. There's definitely something weird going on on iOS.

I have the same project built for iOS (running on iPhone 7) and Android (running on quite old Sony Xperia). So, iOS device is superior to Android device performance wise. However, my DOTween animations run smoothly on Android device, while they are jittery on iOS.

@sandeepsmartest any luck finding the solution?

Btw, I'm also using Unity 2018.2.14f1.

**Comment by Demigiant** [comment]
Can you tell me more of your animations? I'm very confused by this issue and I'm rather convinced that it must be because of something else. Under the hood, DOTween is nothing more than a rather complex math engine, so all it does is math calculations that are then used to set properties of objects and this never had any difference (both logically and realistically) on any platform. I'm wondering if maybe those objects' Transforms or other properties are having issues being changed every frame on iOS? :B

**Comment by nikomikulicic** [comment]
I understand. I also find it quite weird. I see no reason why Unity would handle this differently on iOS and Android.

Example 1: I have a map in my game. A map is just a couple of sprites in the background. I can move from city 1 to city 3 and vice versa by tapping on a button. "move" means `camera.parent.transform.DOMove`. So, this animation moves a camera and I think it should have no impact on UI layout. (Possibly important side note, this technically moves a camera parent, and I have couple of cameras as children. One of them is UI camera which is set to mode: camera screen space. I doubt this movement should affect rendering of UI, but you never know).

Example 2: I have a Card object which has a couple child objects like background image, some stats, some texts. These are indeed UI objects, but are layouted in code only once upon creation. No auto layout components are used (except, maybe TextMeshPro does something from within). I can drag a card around with my finger using `DOLocalMove`. While dragging, card's parent becomes a Canvas object so, even though a card is a UI object, layout and graphics update should not affect the rest of the UI.

Example 3: I have a collection of Card objects in a ScrollRect. I manually do the layout. Parent has Canvas component so layouting should not affect the rest of the UI. When scrolling left-right through cards I use `DOTween.To` and manually set offset for a ScrollRect.

All of these are a lot smoother on Android.

**Comment by nikomikulicic** [comment]
Seems like DOTween was not the issue for me after all. This worked for me:
`Application.targetFrameRate = 60;`
