### ISSUE TITLE
"Couldn't load Modules system" when using managed code stripping.

### ISSUE THREAD

**Issue by PixelEnvision** [Demigiant/dotween#287]
Hi,

I've recently switched to 2018.3 and while trying managed code stripping I've ended up with "Couldn't load Modules system" error on iOS. A search lead me to one of the closed issues and based on the information I've found there I've come up with a fix.

Adding the class you've mentioned "AppDomain.CurrentDomain.GetAssemblies()" to link.xml to preserve it, fixed the issue for me, at least there is no error in the logs anymore.

Maybe you can add PreserveAttribute to that class which should remove the need for a link.xml? 
https://docs.unity3d.com/ScriptReference/Scripting.PreserveAttribute.html

Just wanted to share...

**Comment by Demigiant** [comment]
Ahoy!

Thanks for the info :)
I checked this out, but I have two problems:
1. that I can't use the PreserveAttribute in DOTween's core, because it's too recent
2. that that method is actually used and thus shouldn't be stripped :|

That said, I'm trying to see if I can use a trick and preserve it via the Modules, which are loose scripts so can use more recent stuff. Hope to have an update tomorrow if all goes well.

**Comment by Demigiant** [comment]
Should've fixed it :) Can you try [this new version (1.2.195)](http://dotween.demigiant.com/tmp/DOTween_1_2_195.zip) and let me know if it solves it? :)

**Comment by PixelEnvision** [comment]
Yup 👍 I've just tested it and I can confirm 1.2.195 solves the issue.

**Comment by Demigiant** [comment]
Super \o/ Thanks for the test!
