### ISSUE TITLE
AppendCallback execution order in a Sequence.

### ISSUE THREAD

**Issue by Decavoid** [Demigiant/dotween#30]
**What steps will reproduce the problem?**

```
int number = 0;
Sequence s = DOTween.Sequence();
s.Append(DOTween.To(() => number, i => number = i, 1, 0.1f));
s.AppendCallback(() => { Debug.Log("1. Callback, number is set to 100"); number = 100; });
s.Append(DOTween.To(() => { Debug.Log("2. Getter: " + number); return number; },
    i => { Debug.Log("3. Setter: " + i); number = i; }, 50, 0.1f));
```

**What is the expected output? What do you see instead?**

Expected:
1. Callback, number is set to 100
2. Getter: 100
3. Setter: 68
3. Setter: 51
3. Setter: 50

Actual result:
2. Getter: 1
3. Setter: 32
1. Callback, number is set to 100
3. Setter: 46
3. Setter: 49
3. Setter: 50

**What version of the product are you using?**
DOTween v1.0.770 [Release build]

Workaround is to use `OnComplete`:

```
int number = 0;
Sequence s = DOTween.Sequence();
s.Append(DOTween.To(() => number, i => number = i, 1, 0.1f)
    .OnComplete(() => { Debug.Log("1. OnComplete, number is set to 100"); number = 100; }));
s.Append(DOTween.To(() => { Debug.Log("2. Getter: " + number); return number; }, i => { Debug.Log("3. Setter: " + i); number = i; }, 50, 0.1f));
```

**Comment by oneclickdev** [comment]
any progress/workaround/suggestions?

**Comment by samdze** [comment]
Sequences made entirely of callbacks also execute in wrong order.

**What steps will reproduce the problem?**
```
Sequence seq = DOTween.Sequence();
seq.SetAutoKill(false);
seq.AppendCallback(delegate { Debug.Log("1"); });
seq.AppendCallback(delegate { Debug.Log("2"); });
seq.AppendCallback(delegate { Debug.Log("3"); });
seq.AppendCallback(delegate { Debug.Log("4"); });
seq.AppendCallback(delegate { Debug.Log("5"); });
```

**What is the expected output? What do you see instead?**
Expected:
1
2
3
4
5
Actual result:
4
5
3
1
2
**What version of the product are you using?**
DOTween v1.1.340 [Compatibility build]

The sequence runs if played with `PlayForward`, however it does not when the sequence is completed and `PlayBackwards` is called.

This issue prevents me from using sequences made only of callbacks as the documentation states. And it would also be useful to be able to execute them backwards.

**Comment by Demigiant** [comment]
Hi,

Time is truly important (this is a tween engine after all :P), so things/callbacks that happen at the same exact time are fired randomly, because the only order is time.

If you want something to be called after something else, just add a slight timegap between the two (even if only 0.0001), so you can play it backwards.

If you want things to happen at the same time but with your desired order, use a single callback:
```
seq.AppendCallback(()=>{
   Debug.Log("1");
   Debug.Log("2");
   Debug.Log("3");
});
```

**Comment by lehtiniemi** [comment]
Thanks for the clarification, I had the same issue again.

I think it is unclear, because Sequences are said to be executed in a certain order. Then when you add a function with AppendCallback, it indicates the callback is appended. When it's not, it should be called JoinCallback instead. This seems to be unclear for other people as well. If I add a bunch of stuff with Append, I expect them to run in sequence, one after another. Especially in a case where I first append a tween and then a callback after it, the callback should most definitely be ran after the tween, not before it's finished.

**Comment by davidejones88** [comment]
Hello @Demigiant !
I am using DoTween 1.2.632 and I have noticed that code such as 

```
        Sequence seq = DOTween.Sequence();
        seq.SetAutoKill(false);
        seq.AppendCallback(delegate { Debug.Log("1"); });
        seq.AppendCallback(delegate { Debug.Log("2"); });
        seq.AppendCallback(delegate { Debug.Log("3"); });
        seq.AppendCallback(delegate { Debug.Log("4"); });
        seq.AppendCallback(delegate { Debug.Log("5"); });
```

now produces always the same output: 1 2 3 4 5 (at least in the Editor) reliably. Did something change in the implementation since 2016?

Also, it is not clear to me what **Adds the given callback to the end of the Sequence.** means in the docs for the AppendCallack method because it seems that the code in the AppendCallack gets triggered in the sequence order, not at the end of the sequence. Could you please clarify?

Thanks for your help!

**Comment by Demigiant** [comment]
Hey!

Yes, I upgraded the system so that even callbacks are now called in the order you added them, even if they're at the same time position :) And about AppendCallback, I just added a clarification to the docs: "Adds the given callback to the end of the Sequence (meaning the current total duration of the Sequence)". Does that sound good?

**Comment by davidejones88** [comment]
@Demigiant 
Your comment and the new phrasing in the docs solve every doubt I had. 
Thank you for your update and your incredible library. Cheers!
