### ISSUE TITLE
Sequence Fixed Time

### ISSUE THREAD

**Issue by Ahmadronagh** [Demigiant/dotween#305]
Hi Anyone Can Help Me , I Want To All My Tween in Sequence Run in 1 Second But Sequence hasn't any Feature for this ?

**Comment by Demigiant** [comment]
Hi,

You can't set the whole time of a Sequence directly, because it's always the result of the duration (considering eventual overlapping elements) of its nested tweens, so you'll have to set those durations accordingly. On a secondary note, you can change the speed of a Sequence at any time by using `mySequence.timeScale`.
