### ISSUE TITLE
How to use DoScale using some anchor point?

### ISSUE THREAD

**Issue by ProgrammingLife** [Demigiant/dotween#307]
I need to scale object but using some anchor point? For example, anchor point at left bottom corner of a sprite. How can I do it?

**Comment by Demigiant** [comment]
There is no scale-around-pivot feature in DOTween. If you're scaling UI you can just set it's pivot through the Inspector though, or otherwise you can place your tweened target inside a parent, set the child so that its left bottom corner is at the center of the parent, and scale the parent instead of the child :P
