### ISSUE TITLE
Adding delay parameter to Restart() causes sequence to not restart at all.

### ISSUE THREAD

**Issue by Shockster218** [Demigiant/dotween#355]
So when calling this method without providing any parameters, the sequence restarts fine. However if I want to add delay, it breaks everything completely.  

Restarts without delay as intended:
`                animationSequence.Play().OnStart(() => { sequenceStarted = true; })
                    .OnStepComplete(() => { animationSequence.Restart(); })
                    .SetAutoKill(false);`

Doesn't restart at all:
`                animationSequence.Play().OnStart(() => { sequenceStarted = true; })
                    .OnStepComplete(() => { animationSequence.Restart(true, 1f); })
                    .SetAutoKill(false);`

**Comment by Shockster218** [comment]
This is a follow up from issue https://github.com/Demigiant/dotween/issues/125 about 2 years ago that wasn't addressed.

**Comment by Shockster218** [comment]
Edit: Reading the documentation I figured that I could just append an interval to the back and it does what I want. However, I'd still like to know whats going on with adding parameters to the restart method. Am I incorrectly understanding what it does?

**Comment by Demigiant** [comment]
[Fixed](http://dotween.demigiant.com/download.php). Now the intellisense explains the different behaviour in case of Sequences and the method doesn't block the Sequence from restarting anymore but simply ignores delays (because delays in Sequences are set as PrependInterval, and always present but unchangeable when calling Restart).
