### ISSUE TITLE
DOShake doesn't return to start position on finish and is random across runs.

### ISSUE THREAD

**Issue by lordlycastle** [Demigiant/dotween#364]
I wanted to check is DOShake meant to return the transform to the start position when it finishes?

See below, it isn't returning to start even with 0 randomness. 
![dotween-shake](https://user-images.githubusercontent.com/11729541/72898581-4ee17b00-3d1c-11ea-8955-9fdbd739ae55.gif)

And even with 0 randomness the shake is not same across runs?

I'm also just shaking in 1, 0, 0 direction but sometimes it moves in Z axis as well.

![dotween-shake-large](https://user-images.githubusercontent.com/11729541/72898795-a97ad700-3d1c-11ea-8c96-8a486cfa1af3.gif)

**Comment by Demigiant** [comment]
That usually happens when you erroneously start another DOShake without the previous one being complete, and so the new starting point is not the original starting point. Can you check if that's what's happening? In which case you should either Complete or Rewind the DOShake before starting another.

**Comment by lordlycastle** [comment]
@Demigiant ahh... you're right when you're right! Thx.
