### ISSUE TITLE
Error when building for UWP

### ISSUE THREAD

**Issue by phuongdong008** [Demigiant/dotween#374]
Hi, I am using the latest version. And here are the errors when I am trying to build for UWP:

Reference rewriter: Error: method `System.Reflection.MethodBase System.Exception::get_TargetSite()` doesn't exist in target framework. It is referenced from DOTween.dll at System.Boolean DG.Tweening.Tween::OnTweenCallback(DG.Tweening.TweenCallback,DG.Tweening.Tween).
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1064)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:208)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
------------------------------------------------------------

Reference rewriter: Error: method `System.Reflection.MethodInfo System.Type::GetMethod(System.String,System.Reflection.BindingFlags)` doesn't exist in target framework. It is referenced from DOTween.dll at System.Void DG.Tweening.Core.DOTweenComponent::Awake().
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1064)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:208)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

-------------------------------------------------------------

Reference rewriter: Error: type `System.AppDomain` doesn't exist in target framework. It is referenced from DOTween.dll at System.Type DG.Tweening.Core.Utils::GetLooseScriptType(System.String).
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1064)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:208)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by phuongdong008** [comment]
![Capture](https://user-images.githubusercontent.com/9625487/74603841-798bdd00-50ea-11ea-9de5-261c8a41cce9.PNG)

I am using Unity 2018.3.14

**Comment by Demigiant** [comment]
Ahoy!
The problem there is that your build settings are excluding C# Reflection libraries from the build (which are necessary for DOTween's startup in order to initialize its modules). It's weird though because I force them to be included. Can you check your build settings to see if you didn't strip them (_Player Settings > Other Settings > Stripping Level_)? Or else switch to IL2CPP which should also work?

**Comment by phuongdong008** [comment]
Hi, thanks for your quick answer.
Unfortunately, there is no stripping level in Other Settings section. 
I can't switch to IL2CPP because Vungle plugin doesn't work with it. 

![Capture](https://user-images.githubusercontent.com/9625487/74605617-4e11ee00-50fc-11ea-841b-02ba530b9031.PNG)

**Comment by Demigiant** [comment]
I investigated more and I'm afraid this is a bug that is unclear if relative to Unity or UWP, which resurfaces now and then. IL2CPP fixes it because it includes the Reflection libraries, but if you cannot switch to that the only other solution is to revert to the pre-modules version of DOTween (v1.1.710, you can download it from [here](http://dotween.demigiant.com/download.php) if you click on **Old Versions and Changelog**).

If you're using only DOTween and not the Pro, just delete the whole DOTween folder, ignore all the errors that will appear, import DOTween v 1.1.710, then re-run DOTween's setup. Backup your project before doing this to be on the safe side though. If you're also using the Pro it might be more complicated because of loose scripts and meta, in which case let me know.

**Comment by phuongdong008** [comment]
Hi,
After I import DOTween v 1.1.710, some errors appear:

Assets\_Scripts\SettingButton.cs(36,13): error CS1929: 'Image' does not contain a definition for 'DOColor' and the best extension method overload 'ShortcutExtensions.DOColor(Camera, Color, float)' requires a receiver of type 'Camera'

I am wondering if DOColor is supported in this version?

**Comment by Demigiant** [comment]
DOColor is supported in v1.1.710 but DOTween's Setup needs to import the DOTween46 library (which is done by automatically renaming "DOTween46.dll.addon" and relative files to "DOTween46.dll" etc). If you didn't run the Setup please run it now, and if you did, maybe something happened because of the reversion to an older version. In which case restart Unity, reimport DOTween 1.1.710 (without deleting the existing files: just overwrite them) and re-run the Setup.

**Comment by phuongdong008** [comment]
Hi, It worked and I built my project to UWP successfully. 
Thanks for your help.

**Comment by Demigiant** [comment]
Great, glad to hear it :)
