### ISSUE TITLE
2dToolkit errors when using asmdef on Unity 2018.4.16

### ISSUE THREAD

**Issue by Nikolay1243** [Demigiant/dotween#378]
@Demigiant 
Hi, as you can see below there are these errors that show up. I dont know how to fix them but I assume they're showing up because 2dToolkit doesnt have its own asmdef? If so, how would I make one for it? If not, do you know how I can fix the errors?
[
![image](https://user-images.githubusercontent.com/4185659/75453642-1dd41600-596c-11ea-920e-4b6d653c1960.png)
](url)

**Comment by Demigiant** [comment]
Hi, and sorry for the late reply, I remember replying to this already but maybe something happened during the posting.

This is happening because you don't have [2D Toolkit](https://www.2dtoolkit.com/) installed, I assume? The 2D Toolkit module must be activated only if you have 2D Toolkit in your project, and if you have it then there's no need for ASMDEF. Run DOTween's Setup again and in the modules section disabled 2D Toolkit :)
