### ISSUE TITLE
DOColor Not Working In _EmissionColor

### ISSUE THREAD

**Issue by Guozifan7** [Demigiant/dotween#389]
` GetComponent<Renderer >().material .DOColor(Color.blue, "_EmissionColor",5f);`

Above is My Code,The initial color is black 
And It works in Unity Editor,But not working after building
I'm really really confused

And I try to change the initial color to any other color such as pink, it works after building,but why?

**Comment by Guozifan7** [comment]
The code above based on having enabled EMISSION in Inspector,
If I don't enable EMISSION in Inspector  , and enable it in my code,it never works after building 
 whatever the initial color is
why?
unity version 2019.3.1f1,DOTween  latest version

**Comment by Demigiant** [comment]
Hi,

I'm not sure of what is happening, but it simply means that the _EmissionColor isn't reachable (not just by DOTween but even by your own custom code), because all DOTween does in that case is use Unity's internal APIs to set the given property color. From what I understand you were trying to use a Material that didn't have emission enabled, so the _EmissionColor property didn't exist.

Cheers,
Daniele
