### ISSUE TITLE
DoTweenPath does not change the starting position in play mode

### ISSUE THREAD

**Issue by Prog-Maker** [Demigiant/dotween#394]
Why does DoTweenPath change its starting position in Editor mode, but not in Play mode?

**Comment by Demigiant** [comment]
Ahoy,

Can you explain me better? I didn't understand the question :B

**Comment by Prog-Maker** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16715097/81468292-003aec80-91f8-11ea-80a0-f4e0c26f7360.gif)
the video is clearly visible

**Comment by Demigiant** [comment]
The editor is a creation mode that is very different from the runtime mode. If you just mean the gizmos path then it's because that becomes fixed after you first create the path (so that it's not recalculated every frame, wichh would impact performance). The path will instead move with your object as long as it's a local path, otherwise its points are in world coordinates.
