### ISSUE TITLE
Sequence.AppendCallback (or InsertCallback) not working

### ISSUE THREAD

**Issue by josephnarai** [Demigiant/dotween#397]
I have the following simple code:

Inside CurrentAudioSource class:

        Sequence = DOTween.Sequence();

Inside the class using the CurrentAudioSource:

        CurrentAudioSource.Sequence.Append(DOTween.To(() => CurrentAudioSource.ClipVolume.Value, x => CurrentAudioSource.ClipVolume.Value = x, 1, fadeDuration).SetDelay(startDelay).OnStart(OnFadeInStart).OnComplete(OnFadeInEnd));
        CurrentAudioSource.Sequence.Append(DOTween.To(() => CurrentAudioSource.ClipVolume.Value, x => CurrentAudioSource.ClipVolume.Value = x, 0, fadeDuration).SetDelay(fadeOutStartDelay).OnStart(OnFadeOutStart).OnComplete(OnFadeOutEnd));
        CurrentAudioSource.Sequence.AppendCallback(() => { Debug.Log("here"); });

And Debug.Log("here"); never gets executed. I've tried putting it between the other two Appends, and I've also tried InsertCallback() and it doesn't work either. The OnComplete and OnStart callbacks work fine.

Please advise.

**Comment by Demigiant** [comment]
Ahoy, you must assign the Sequence in the same method/frame where you fill it, because otherwise it will be locked after one frame.

Inside CurrentAudioSource class:

    Sequence;

Inside the class using the CurrentAudioSource:

```
CurrentAudioSource.Sequence = DOTween.Sequence()    
CurrentAudioSource.Sequence.Append(DOTween.To(() => CurrentAudioSource.ClipVolume.Value, x => CurrentAudioSource.ClipVolume.Value = x, 1, fadeDuration).SetDelay(startDelay).OnStart(OnFadeInStart).OnComplete(OnFadeInEnd));
CurrentAudioSource.Sequence.Append(DOTween.To(() => CurrentAudioSource.ClipVolume.Value, x => CurrentAudioSource.ClipVolume.Value = x, 0, fadeDuration).SetDelay(fadeOutStartDelay).OnStart(OnFadeOutStart).OnComplete(OnFadeOutEnd));
CurrentAudioSource.Sequence.AppendCallback(() => { Debug.Log("here"); });
```

**Comment by josephnarai** [comment]
Thanks, that fixed it.

But I'm confused why Appending the other two Tweens worked and the callback didn't? Shouldn't the other two Tweens also have been locked out?

Great plugin BTW - thanks for the awesome work :)

**Comment by josephnarai** [comment]
And one last question. I'm using this same Sequence variable multiple times sequentially.

Should I add a kill before assigning the new sequence?

CurrentAudioSource.Sequence?.Kill();
CurrentAudioSource.Sequence = DOTween.Sequence();

**Comment by Demigiant** [comment]
Thank you :) And uhmmm I skipped too fast through your first question, the OnComplete and OnStart shouldn't have been called either. I'm thinking that, since they couldn't be appended to the Sequence, they started normally as Tweeners and thus they worked, while instead the Sequence callback was forbidden. If you activate ErrorsAndWarnings log mode in DOTween's Utility Panel's Preferences you should get a warning when trying to add things to a Sequence that is already locked, but I'll investigate about the "Tweeners still working thing" :P

About the other question: absolutely yes, kill the Sequence before reusing the variable. Otherwise it will remain stored inside DOTween's tweens cache.

**Comment by josephnarai** [comment]
Thanks!

OnComplete and OnStart were both called - this is why I was confused!

Thanks again - much appreciated!

J
