### ISSUE TITLE
"AudioSource" does not contain a definition for for "DOFade"

### ISSUE THREAD

**Issue by savioti** [Demigiant/dotween#407]
and the DOTween methods intellisense shows for an AudioSource are somewhat generic:

![image](https://user-images.githubusercontent.com/34958918/84274154-e4cc4580-ab05-11ea-8874-4c6334145ecf.png)

And it's definitely an AudioSource:

![image](https://user-images.githubusercontent.com/34958918/84274200-f3b2f800-ab05-11ea-9fd3-544eff880cbd.png)

Thanks in advance.

**Comment by Demigiant** [comment]
Ahoy!

That can happen because of two reasons:

1. You didn't enable the Audio module in DOTween's Utility Panel > Setup
2. You have another class in your Unity project called AudioSource which has no namespace, and which will "eat" all references to Unity's own AudioSource for every asset that relies on it. In that case you should search for said class and add a namespace to it.

P.S. I'm closing the issue but let me know if for some reason it's not solved.
