### ISSUE TITLE
OnStart tween gets struck

### ISSUE THREAD

**Issue by Audry1904** [Demigiant/dotween#411]
On start of game, dotween plays 0.25 % of animation then pauses(delays for a sec or 2 sec) then plays rest of it. 
   
    void Start()
    {
        plate1.sprite = plate2.sprite = defaultImage;
        plate1.DOFade(1, 0.25f);
    }

**Comment by Demigiant** [comment]
Ahoy,

I can assure you that DOTween is not pausing by itself unless you're pausing it (which I assume you're not), so the reason is external.
I'd assume your game has a big lag at startup and everything pauses, not just DOTween? Or maybe there's something that is setting Unity's timeScale to 0 for a little while?

**Comment by Audry1904** [comment]
Hi, 
I closed and opened the unity editor, but it didn't fix it.

Then I did reimport all inside unity. Closed and opened the editor again. And its fixed.

Thank you for your support.

**Comment by Demigiant** [comment]
Weird :O But glad you solved it :)
