### ISSUE TITLE
DoShake doesn't return to original values when finished?

### ISSUE THREAD

**Issue by elvisish** [Demigiant/dotween#427]
Is there a way of tweening the shake back to it's original value? It always ends up in a totally different position and using DoRewind doesn't help either.

**Comment by Demigiant** [comment]
That happens if you start another shake before the previous one has finished (and you didn't complete/rewind it): in that case the original value will become the new starting point. Be sure you complete or rewind the previous tween (or even better, use the same non-autoKill tween and Restart it) before starting a new one and it the original value will stay the same :)

**Comment by elvisish** [comment]
Thanks, I tried rewinding the after waiting for the same length of time and the X position is still wrong, although the X and Z seem to be returned (although they started at 0.5 and 0.6 respectively, whereas X started at 0). I'm also making sure it only does it once and it just doesn't return to the original value?

EDIT: if I set the X position to, say, 0.1, it gets closer with returning to 0.09, but 0 just gives me weird things like -8, -1.05 and -3.21810

EDIT again: Yes, there seems to be an issue with the tween returning back to 0 if the position starts at 0, it works fine if I set it to 0.1, 0.01 or 0.001, but it breaks if I use 0.0001. I'm tweening a child object, btw.

**Comment by Demigiant** [comment]
I tried to replicate here but the child goes back to 0 correctly. Can you post me the code you're using?

P.S. -8 seems really impossible (a tween knows its end value from the beginning, and to avoid floating point imprecision forces its target to that exact value when it completes). Is it possible that you have other non-shake tweens acting on the same target, which would displace it before the shake restarts?

**Comment by elvisish** [comment]
I’m using Flowcanvas which is probably causing the problem, and I’m using Fast Play Mode. I’m not using the flowcanvas extensions but rather the direct reflected shortcuts, so theoretically it should work the same as code, but it might be a flowcanvas issue in this case. Here's how it's set-up:
![image](https://user-images.githubusercontent.com/16231628/89707310-cac3ad80-d964-11ea-8e62-9a96ac6b122a.png)

**Comment by Demigiant** [comment]
I tried using the same values Flowcanvas is using but still it work perfectly here. I never used Flowcanvas but I don't see how it could cause the problem unless it either changes the child position before the tween or runs another shake tween before a previous one has ended. Please bear with me if I insist that we should try to check for other shake/move tweens running on the same target: I had many issues sent to me in the past about DOShake not returning at the same exact position, and each time the problem was that in the end :P

How does the "Do Once" node work? Even if the PlayerShake SIGNAL CALLBACK happens again ignores it after the first time? Is it possible that it's not doing that? Or that you have a copy of this same Flowcanvas (not sure if that makes sense) which is doing the same thing again?

Do you have a way to add DOTween's callbacks via Flowcanvas? A good test would be to add an OnStart that logs "Start shake + child position" and an OnComplete that logs "End shake + child position", to see if multiple OnStart are called before the first OnComplete is.

**Comment by elvisish** [comment]
> I tried using the same values Flowcanvas is using but still it work perfectly here. I never used Flowcanvas but I don't see how it could cause the problem unless it either changes the child position before the tween or runs another shake tween before a previous one has ended. Please bear with me if I insist that we should try to check for other shake/move tweens running on the same target: I had many issues sent to me in the past about DOShake not returning at the same exact position, and each time the problem was that in the end :P
> 
> How does the "Do Once" node work? Even if the PlayerShake SIGNAL CALLBACK happens again ignores it after the first time? Is it possible that it's not doing that? Or that you have a copy of this same Flowcanvas (not sure if that makes sense) which is doing the same thing again?
> 
> Do you have a way to add DOTween's callbacks via Flowcanvas? A good test would be to add an OnStart that logs "Start shake" and an OnComplete that logs "End shake + child position", to see if multiple OnStart are called before the first OnComplete is.

I think Flowcanvas might be causing phantom dotweens or doshakes to happen if they've been triggered by events, even if you remove them and the only way I can fix it is by restarting Unity. I'll report it on the FC forum and try and figure out what's going on, I'll post back here with more info once I can. Really sorry about the inconvenience!

**Comment by Demigiant** [comment]
No inconvenience :)

P.S. If you're not tweening anything else at that moment, you could have Flowcanvas call a static DOTween.KillAll(true) immediately before the shake, where the "true" parameter tells the kill operation to also complete all running tweens (so any shake will be reset).
