### ISSUE TITLE
Problem working with git repository

### ISSUE THREAD

**Issue by luis-gl** [Demigiant/dotween#428]
Hi, I am using this in a project and I want to upload it to a git repository to work on both my pc and my laptop when I am away. All good if I create a project, import the assets and then upload them to the repository. However, when cloning the repository to the other device, I get several errors about namespaces and assemblies coming from the folder where DoTween was imported. Is there a fix for this? I'm using Unity 2019.3.6, but this happens in whatever version I tried.

**Comment by Demigiant** [comment]
Ahoy,

There should be no problem cloning repos that contain DOTween, unless your git repo was set to exclude DLL, in which case DOTween was excluded from git. Can you check that?

**Comment by luis-gl** [comment]
Is that seen in the .gitignore file? because I don't see any annotation about exclude dll's.
Here is my .gitignore file:
![Captura](https://user-images.githubusercontent.com/42353343/89699080-51877480-d8ea-11ea-8475-8865baad27c9.PNG)

**Comment by Demigiant** [comment]
1. Have you checked if when you clone the repo you have DOTween's DLLs or not? Just to be sure this is the problem
2. I don't see DLL ignores there but check [this thread](https://stackoverflow.com/questions/15515729/git-repository-ignoring-all-dlls/15515842) about global git ignores and a similar problem

**Comment by luis-gl** [comment]
Hey! I tried creating a new repo from one device and notice that in the other there was a gitignore global, changed the file to acept DLL's and it worked. So no problem anymore!

Thanks for the help :D

**Comment by Demigiant** [comment]
Great ^_^

**Comment by fmoyano** [comment]
Hi!

I'm experiencing the same problem: I've cloned a repository and have lots of errors of this kind: "The type or namespace name 'Core' does not exist in the namespace 'DG.Tweening' (are you missing an assembly reference?).

I've seen that all the dlls are present, yet they are tracked by LFS. Can this be the reason for the errors?

EDIT: Actually that was it! The problem was that I had not Git LFS installed on the machine cloning from the repository, so I guess that I only had the files pointers, but not the dlls themselves. So the steps if using Git LFS are: 1) Install Git LFS and initialize; 2) Clone the repo
