### ISSUE TITLE
Can not use DOTween on 2020.1

### ISSUE THREAD

**Issue by AntonPetrov83** [Demigiant/dotween#429]
Hi!

So Unity has released 2020.1 and all purchases were moved to the Package Manager (fyi: I have purchased a Pro version.)

I was switching to asmdefs and I was hoping to use DOTween but looks like it has no assembly definitions. 
At first DOTween Utility Window was hanging with "Continuing importing process..." message.

And I did a full reinstall of dotween but now I have no DOTween Utility Window in Tools menu at all.

What is going on? Do you need help on solving these issues?

Thank you.

**Comment by Demigiant** [comment]
Ahoy!

If you import a package via the "My Assets" section of the Package Manager it will be imported the same way it was from the Asset Store (so fully included in the project), so your issue is not related to that (but thanks for the help offer).

Is it possible that you have multiple DOTween installs? A very important step when updating to the last version is to first move the "Demigiant" folder inside the "Plugins" folder if it's not there already (more details [here](http://dotween.demigiant.com/support.php)). If you still have the "Continuing importing process..." message please close Unity, re-open it and simply re-run DOTween's Utility Panel setup.

**Comment by Demigiant** [comment]
P.S. I had this issue happen randomly and very rarely to some users in the past, but a close-and-reopen Unity always worked.
