### ISSUE TITLE
Any way to instantly jump to a specific animation time?

### ISSUE THREAD

**Issue by alexinfurs** [Demigiant/dotween#433]
Hi, I wonder if there's a simple method to jump directly to a specific animation time like Goto but instantly

I'm working on a rhythm game and I need a total control over animations to keep everything in sync, so I want to create an animation with easing and other cool stuff DOTween provides, and directly manage it frame by frame

Is it possible?

Thanks a lot for your support

**Comment by Demigiant** [comment]
Ahoy!

If you chain a [SetUpdate(UpdateType.Manual)](http://dotween.demigiant.com/documentation.php?api=SetUpdate), you can then animate those manual tweens via [DOTween.ManualUpdate](http://dotween.demigiant.com/documentation.php#ManualUpdate).

**Comment by alexinfurs** [comment]
Hi Daniele!
Thanks for your support

I knew about ManualUpdate, but unfortunately it doesn't seem to be exactly what I'm looking for, because ManualUpdate updates all the manual tweens with the same DeltaTime while I need to manage them independently.
It'd have been super useful if it there was an instance method too

**Comment by Demigiant** [comment]
[Here you go](http://dotween.demigiant.com/tmp/DOTween_1_2_475.zip) :) I added a `tweenInstance.ManualUpdate` method, which will force the update regardless of the UpdateType you assigned to the tween (though you'll want to give it a Manual UpdateType so that it's not updated automatically). Consider that the tween will behave like a normal tween, so if it's paused nothing will happen if you updated it manually.

**Comment by alexinfurs** [comment]
WOW! That's great!
Can't wait to test it

Thanks a lot!!

**Comment by Demigiant** [comment]
Let me know ^_^
