### ISSUE TITLE
'Outline' does not contain a definition for 'effectColor' or for 'effectDistance'

### ISSUE THREAD

**Issue by Cerzix** [Demigiant/dotween#437]
I imported DoTween into my project after copying some scripts from a Unity demo.

On import the Console shows me a couple error messages all ending with the title text in the "DOTweenModuleUI.cs"-Script.

I've checked inside of the mentioned Script and this is one of the methods this issue appears in:

```cs
        public static TweenerCore<Color, Color, ColorOptions> DOFade(this Outline target, float endValue, float duration)
        {
            TweenerCore<Color, Color, ColorOptions> t = DOTween.ToAlpha(() => target.effectColor, x => target.effectColor = x, endValue, duration);
            t.SetTarget(target);
            return t;
        }```

To fix it temporarily, i can just remove DOTween from my project, but id like to use it because its very useful.

Greetings, Cerzix

**Comment by Cerzix** [comment]
Here's the complete text of 1 such error:

Assets\DOTween\Modules\DOTweenModuleUI.cs(172,81): error CS1061: 'Outline' does not contain a definition for 'effectColor' and no accessible extension method 'effectColor' accepting a first argument of type 'Outline' could be found (are you missing a using directive or an assembly reference?

**Comment by Demigiant** [comment]
Hi,

This happens when you have another script named exactly like Unity's ("Outline") and which has no namespace, in which case it will eat all references to Unity's own classes (in short, DOTween is trying to refer that Outline class instead of Unity's). To fix it look inside your code to find a class named "Outline" (it's almost surely in one of your assets) and add a namespace to it. Also, if you could tell me what asset contains it I would be grateful so I can warn the developer, because scripts without namespaces like that break other assets and in theory they're not allowed by Unity, but sometimes it happens :P

**Comment by Cerzix** [comment]
Hi there,

thanks for the quick response, that was indeed the problem.

I downloaded an asset that included a shader and a script to draw an outline around objects behind walls for example.
Assetstore-Link: https://assetstore.unity.com/packages/p/quick-outline-115488

Cheers, Cerzix

**Comment by Demigiant** [comment]
Ah! There it is! Thank you, it's happened in the past that "Outline" had this problem but I was never told what asset was responsible. Will try to contact the author :)

**Comment by Demigiant** [comment]
I wrote the author but also implemented a
`using Outline = UnityEngine.UI.Outline;`
enforcer in DOTween Pro, so these issues won't happen again from next update

**Comment by Cerzix** [comment]
Awesome, appreciate the effort. Keep up the good work :D
