### ISSUE TITLE
Tween startup error - how to track down which tween?

### ISSUE THREAD

**Issue by emrys90** [Demigiant/dotween#438]
I'm getting an occasional error about starting a tween due to a null transform. While this would probably be a simple fix if I knew where this was occurring, the error message doesn't seem to provide any details as to where this is happening at. Any ideas on how to track down a class/line number or something?

**Comment by Demigiant** [comment]
Hi,

In DOTween's Preferences (inside DOTween Utility Panel) you can activate the debug mode (which requires safe mode to be active): that will capture the error and additionally store the tween's target, so that when NULL target errors happen it will tell you the target's original name. Be sure that you haven't set LogBehaviour to ErrorsOnly in the Preferences because in that case, since safe mode doesn't generate these errors, you won't get any report.

**Comment by emrys90** [comment]
Thanks! I totally missed that setting when I was looking through there, I feel blind now lol.

However, I turned on the debug mode, and I didn't seem to get any additional logging. Log Behavior is set to Default.

**Comment by Demigiant** [comment]
Ah, so sorry, I forgot to mention that you also need to check the "Store GameObject's ID" toggle inside DEBUG MODE :B

**Comment by AldeRoberge** [comment]
If anyone else finds themselves in the same situation, trying to find the DEBUG MODE without any success, it's at the bottom of the DOTween panel : 

![image](https://github.com/Demigiant/dotween/assets/4276275/58a663e1-7927-4537-9504-a1fcc3b3cc86)
![image](https://github.com/Demigiant/dotween/assets/4276275/db50a3e7-bf21-4cfb-b302-0f29a960fb5a)

:)
