### ISSUE TITLE
Infinite Loops and -1

### ISSUE THREAD

**Issue by baldodavi** [Demigiant/dotween#450]
With this code
```
public Sequence PulseTime() {
    Sequence seq = DOTween.Sequence();
    seq.Append(ContainerTweens.DOFade(clessidra, 1f, baseClexFreq));
    Sequence loopSeq = DOTween.Sequence();
    loopSeq.Append(ContainerTweens.DOFade(clessidra, 0.3f, baseClexFreq * 2));
    loopSeq.SetLoops(1000);
    loopSeq.Loops();
    seq.Append(loopSeq);
    seq.OnKill(() => {
      ContainerTweens.DOFade(clessidra, 0.75f, 0).Play();
    });
    return seq;
  }
```
Unity is able to loop loopSeq 1000 times in expected way.
Using
```
loopSeq.SetLoops(-1);
```
Unity does not start loop, but I'm expecting an infinite loop.

Any idea about? Something wrong in my code?
Thanks.

**Comment by Demigiant** [comment]
Ahoy! You can't nest a Sequence/Tweener with infinite loops inside another Sequence. That's because a Sequence needs to know how much one of its single loop cycles would last, and infinite nested loops would prevent that. That said, you can always use int.MaxValue instead, which will be semi-infinite unless your game/app runs for a very, very long time.
