### ISSUE TITLE
Allow tweening for double data types and custom types

### ISSUE THREAD

**Issue by ScriptGeek** [Demigiant/dotween#46]
I'm working on a project that needs to tween doubles, due to the requirement of massive scaling with extreme precision.  It appears that floats are the closest I can get for tweening with DOTween at the moment, is it possible to use DOTween to implement tweening for doubles with double values as targets?

Also, many double values that I'm working with are represented in a custom type similar to Vector3, but instead of floats it uses doubles.  Is there support for creating and using custom types?

For example, like the float tween, I'd like to be able to use doubles:
double target = 100000000000000000;
double current = 0.0;
DOTween.TO(()=> current, x => current = x, target, 5);

An example usage with of a custom type:
CustomV3 target = new CustomV3(0.0,0.0,1000000000000000,10);
CustomV3 current = someObject.GetCustomV3();
DOTween.TO(()=> current, x => current =x, target, 15);

**Comment by Demigiant** [comment]
Hi,

I added the Double implementation to my todo list. I might be able to do it tomorrow, but I'm not sure because I'm crunching hard on various projects these days.

About creating custom types implementations, yes, it can indeed be done via custom plugins. I'll try to whip up an example for that too.

Cheers

**Comment by ScriptGeek** [comment]
That's great news, thank you!  I'm not in a super huge rush, so whenever you get to it is fine.  I noticed that iTween allows for doubles, but DOTween's performance benchmarks smears iTween into the dirt.

**Comment by Demigiant** [comment]
[Voila](http://dotween.demigiant.com/download.php) :)

Also, I updated the [examples](http://dotween.demigiant.com/examples.php) to show how to create a custom DOTween plugin (and I also updated the list of supported formats to include long, ulong, and Color, which were present since a long time but I forgot to mention them on the website).

**Comment by ScriptGeek** [comment]
That's awesome, thanks for busting this out!  This appears work for my needs.  I just want to point out a little thing in regards to the target value for the overloaded method using doubles for getter and setter parameters, it currently takes a float for the target.  Is this intended by design?

**Comment by Demigiant** [comment]
Damn me! No, that's an error, sorry. I fixed it now. You can get it [here](http://dotween.demigiant.com/tmp/DOTween_1_1_015.zip) in the meantime.

**Comment by ScriptGeek** [comment]
Sorry it took me so long, but I finally got around to checking this out again.  This works great and thanks again for the support!

**Comment by Demigiant** [comment]
Great :)
