### ISSUE TITLE
Installing DOTween in 2020.3.5f1 not working

### ISSUE THREAD

**Issue by octoConnors** [Demigiant/dotween#529]
https://imgur.com/a/XFmgVLc
When I open the Utility Panel it's blank and my cursor flashes that loading circle.

I'm getting these errors: https://imgur.com/CJRhVSM

**Comment by Demigiant** [comment]
Ahoy,

It seems that for some reason it can't create the Resources folder and the
relative file inside. Is it possible that you have some kind of write
privilege on the project's path, or a weird naming pattern that blocks
normal path creation?

In the meantime, could you try creating the Resources folder yourself (in
the root of your project) and see if at least the file creation proceeds
correctly?

Cheers,
Daniele

**Comment by octoConnors** [comment]
Hi,
I did try creating a Resources folder! Unity actually deleted it afterwards. I've been trying to figure out why.

**Comment by octoConnors** [comment]
Update: When I open the project and click "Open DOTween Utility Panel" to setup DOTween, I can see the Resources folder being created and destroyed repeatedly in the file explorer.

**Comment by Demigiant** [comment]
If you can't create the Resources folder yourself something is very weirdly wrong in your project (which then blocks DOTween and any asset that tries to create a Resources path). Is it possible that you have a virus, or some weird superlong project path (or that includes weird characters)? Or that you have some other asset/editor-code that is deleting the Resources folder on loop? I never heard of such a problem so I don't know how I can help.

P.S. Marking this as invalid because it's not related to DOTween, so it won't clutter the issues, but feel free to write more

**Comment by Demigiant** [comment]
P.S. if you create the Resources folder via file explorer, does Unity destroy it anyway? And if you tried this already, what if you create it via the Unity Project panel?

**Comment by octoConnors** [comment]
I got things working! This behavior occurs if you take the contents of the folder in the DOTween download (the folder called DOTween) and drag them directly into the Assets folder. I had installed it wrong. Of course it works correctly if you put the folder itself into Assets with everything inside. This really ought to be in the readme file or something.
