### ISSUE TITLE
FeatureRequest: Animation

### ISSUE THREAD

**Issue by Darelbi** [Demigiant/dotween#54]
Is there any chance DOTween will in future supports animations/animations components:

```
GetComponent< Animation>().DOPlay()
      .OnComplete( ()=> {
      Debug.Log("AnimCompleted!");
});
```

Is there any shortcut for simply waiting? (maybe I'm missing it)
actually my solution for waiting, is animating a dummy float value for X seconds.

Thanks for this great library

**Comment by Demigiant** [comment]
Ciao Dario!!!

Supporting Unity Animations sound interesting but also kind of useless from my point of view, since that is more of a missing feature (one of many regarding Animations) on Unity's side, that I don't think would be wise to fix on DOTween's side.

About waiting, check out [DOVirtual. DelayedCall](http://dotween.demigiant.com/documentation.php?api=DelayedCall) ;)

**Comment by Darelbi** [comment]
Thanks Great! I'll submit feature request on UnityForum then :)
