### ISSUE TITLE
ShakePosition 0 randomness has no effect

### ISSUE THREAD

**Issue by adrianmavenhut** [Demigiant/dotween#57]
Hello.

Selecting a shake position, Randomness 0 value 
- should disable the random, and always shake with the same strenght, from my understanding.
- happens - the shake is done still at random values.

Another problem is that sometimes the randomness is almost 0, and has no visual effect.

**Comment by dhissami** [comment]
I am also experiencing this issue.

**Comment by Demigiant** [comment]
Ahoy,

The randomness indicates the axis randomness. Read more [here](http://dotween.demigiant.com/documentation.php?api=DOShakePosition__1), but in short, a randomness of 0 only shakes along one random axis instead of all of them.
If you want to shake always with the same strength, you have to set fadeOut to FALSE. Grab the latest DOTween version from [here](http://dotween.demigiant.com/download.php) if you don't have it, because I implemented the fadeOut option only recently.

Cheers,
Daniele

**Comment by adrianmavenhut** [comment]
Ok I see, but that's not logical or intuitive. If a value is 0 but still has effect, then how you disable it? 👎 
shake always with the same strength - set fadeOut to false. What value the randomness should be? to have the same value always, not random?

**Comment by Demigiant** [comment]
Sorry for the late reply!
Having the same value always and not random would cancel the meaning of a shake. For that you can do a regular tween with a custom curve or a Flash ease.
Randomness is the axis randomness. I'll correct the docs to make it clearer.
