### ISSUE TITLE
Scene reloading stops tweening functionality

### ISSUE THREAD

**Issue by kevin-uk-dev** [Demigiant/dotween#59]
This seems a strange one and might be an interaction with Unity and the way it loads/destroys scenes. 
Load scene A tweening works.
Load scene B tweening works.
Return to scene A, tweening does not work. Code to do tweening is called but does nothing and no errors are produced.

**Comment by Demigiant** [comment]
There might be some null reference around which silently kills the tween. Try to disable safe mode from the preferences, and you should get more feedback.

**Comment by kevin-uk-dev** [comment]
Thanks for coming back to me. I've reworked things to not use two scenes. Will take a look at disabling safe mode as that seems interesting.

**Comment by Demigiant** [comment]
Great, and sorry for being so late to get back to you.

**Comment by meduhealth** [comment]
Hi, I have exactly the same issue. When reloaded this first scene, after playing the second scene, the tweens won't start anymore. You see in the inspector that the tweens are made, see the screenshot. But the twees are not playing.. If guess it has something to do with references? 

I'm using to pro version and we are ready for launch in both app store.. but this issue is holding us back. Hopefully you can respond quick. Thanks.
![screenshot 2017-02-26 15 02 41](https://cloud.githubusercontent.com/assets/1632666/23340360/01cf29dc-fc35-11e6-951e-f16d75893040.png)

**Comment by Demigiant** [comment]
Hi!

I see that you have your Unity's timeScale set to 0 ;) Unless your tweens are set to be timeScaleIndependent, Unity's timeScale will affect them.

Cheers,
Daniele

**Comment by meduhealth** [comment]
:) I'm happy you saw that! So has nothing to do with DOTween! Thanks for the quick answer and keep up the good work! All the best!

**Comment by Ajk4** [comment]
I had same thing while tweening on RectTransform. After reloading the SAME scene it would not work.

Workaround that worked for me:

Just call DOTween.clear() like this:

        // TODO Without Clear it won't work.
        DOTween.Clear(true);
        // TODO Reload current scene
        SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex);  `

**Comment by LubomirKurpel** [comment]
Ajk4 Man you saved me like a ton of work! Thank you! Works like a charm. Was searching for a solution for quite a while.

**Comment by tomerpeled** [comment]
DOTween.Clear(true);

Solve it for me as well!
Thanks!

**Comment by CraneInForest** [comment]
DOTween.Clear(true);

It's save my life.Thanks!

**Comment by Romaleks360** [comment]
Same issue here! This only happens for me when Recycle Tweens in Preferences is set to true; and in this case, Clear(true) does the thing.

**Comment by el-torito** [comment]
> I had same thing while tweening on RectTransform. After reloading the SAME scene it would not work.
> 
> Workaround that worked for me:
> 
> Just call DOTween.clear() like this:
> 
> ```
>     // TODO Without Clear it won't work.
>     DOTween.Clear(true);
>     // TODO Reload current scene
>     SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex);  `
> ```

Hi I am new with Unity and I am using playmaker and Dotween could you guide me where to put put the script?

**Comment by Elnurv47** [comment]
> 
> 
> Hi!
> 
> I see that you have your Unity's timeScale set to 0 ;) Unless your tweens are set to be timeScaleIndependent, Unity's timeScale will affect them.
> 
> Cheers,
> Daniele

thanks you very much!

**Comment by el-torito** [comment]
Hi thank you for the response. I checked unity’s time scale and it is currently set at 1.

How do I set timeScaleIndependent? I am using playmaker and I don’t know anything about coding. 

Thank you

**Comment by DevaWu** [comment]
> > I had same thing while tweening on RectTransform. After reloading the SAME scene it would not work.
> > Workaround that worked for me:
> > Just call DOTween.clear() like this:
> > ```
> >     // TODO Without Clear it won't work.
> >     DOTween.Clear(true);
> >     // TODO Reload current scene
> >     SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex);  `
> > ```
> 
> Hi I am new with Unity and I am using playmaker and Dotween could you guide me where to put put the script?

You can buy this one : [https://assetstore.unity.com/packages/tools/visual-scripting/playmaker-actions-for-dotween-by-doozy-49222](https://assetstore.unity.com/packages/tools/visual-scripting/playmaker-actions-for-dotween-by-doozy-49222)

**Comment by irtezamasud-blendbrain** [comment]
Yeah thats the unity issue why it wasn't working in most of the cases. While I reloaded back to my previous scene Somehow Time.timescale set to 0 (I didn't do a single thing); I figured it out from project settings> Time. That's why tween isn't playing.

I faced this "Time" issue several times with unity while I hadn't done nothing.(Maybe a bug).
Setting time.timescale to 1 at the start or awake will fix the issue and tween will work perfectly.

**Comment by rcstamp** [comment]
`DOTween.Clear(true)` is a workaround for now, even though TimeScale was 1 for me, tweens were acting super weird.
If I disabled then re-enabled the `[DOTween]` instance in the scene, tweens would act normally again.. :/

**Comment by morneluckybeard** [comment]
Having the same issue, after reloading the scene. Tweens would either not work or show up at odd times.

**Comment by imniko** [comment]
I think this happens sometimes while reloading a scene with a tween still running, does not happen every time though. Strange that this 6 year old bug is still happening. Anyway, I have found calling `DOTween.KillAll();` before scene reload or after the scene is reloaded fixed the issue for me.

**Comment by Demigiant** [comment]
I admit I never gave much importance to this issue (sorry for that) but only because I always considered (also from most comments above) that it's not a bug but some non-DOTween issue (like TimeScale set to 0). If you can replicate this in a sample package and attach it here I'll take a look (next week)

**Comment by imniko** [comment]
I attached below a sample unity project that replicates the issue, only a sample scene and a script is added, hope this helps track down the issue.  

[DoTweenTest.zip](https://github.com/Demigiant/dotween/files/6980090/DoTweenTest.zip)

**Comment by Demigiant** [comment]
Thank you! As soon as I'm at the computer (should be next Monday) I'll check this out and see :)

**Comment by imniko** [comment]
@Demigiant sorry for pinging you, but any update on this?

**Comment by Demigiant** [comment]
@imniko So sorry, my working laptop has been hard to fix and once done I prioritized other things.
I just checked your test example and I can see nothing wrong. I mean, the error happens because you're loading a new scene while a tween is still running, and thus the tween finds itself without a target because it was destroyed by the load operation. Uncommenting the `DOTween.KillAll` line avoids the error because it kills the tweens before reloading the scene. Alternatively, you can enable safe mode in DOTween's Preferences which takes care of cases like these, aka tweens' targets being destroyed or becoming NULL while a tween is running. Please let me know if I'm missing something.

NOTE: If two tweens (your delayedCall and your shake tween) happen in the same frame the order of which one happens first is not pre-determined (actual order is optimized in-engine), so in your case the delayedCall-reloadScene is happening before the shake tween can complete its final frame

**Comment by imniko** [comment]
Now that I think about it, its actually the expected behavior, but sometime its frustrating because maybe some tween is running in the background (UI/Button tweening or some other effect) and user presses next button or scene is reloaded. Occasionally it triggers this exception specially for looping tweens if you don't kill the tweens when OnDestory() is called. These are some things one has to keep in mind, but no mention about it in documentation for an inexperienced dev. 

In a project I was heavily using DoVirtual.DelayedCall, but then I was getting many exceptions in cases because SceneReloading would not kill this function, don't remember why SafeMode didn't stop the exceptions. So I had to switch a co-routine based Delay function which used current Monobehavior context so that the function would stop working when game object is destroyed.

**Comment by Demigiant** [comment]
I have information about that in a couple places on the website, but you're right that I should make it more evident and more comprehensive, also because it's missing from the Documentation page (it's in the Get Started and Support pages). Safe mode should take care of DOVirtual.DelayedCall too, I will ponder about why it didn't in your case: are you sure it was enabled?

**Comment by SavedByZero** [comment]
For me, DOTween.clear(true) works, but it’s dangerous — when I return to the scene and some of my tweens end, the game force-pauses with an exception about trying to access destroyed objects. I never have this issue unless I call the clear method with true right before leaving and reloading the scene, oddly enough.

**Comment by Demigiant** [comment]
Have you tried `DOTween.KillAll()`? It's the recommended API, while Clear should be called only if you don't want to use tweens ever again from that point onward (I mean, it works like KillAll but also removes all the necessary stuff needed to run tweens, which will then have to be recreated from scrap the next time you use a tween, while KillAll kills and removes all tweens while maintaining the tween engine available for later use)

**Comment by SavedByZero** [comment]
Yeah. KillAll() didn’t work, unfortunately — any time any scene loads before this one, then loads into this scene, when I try to tween some dots on the screen they just don’t move at all (but everything else functionally works — they die at the end of the world-be tween as they should, you just don’t see them moving). I’ll keep playing with it.

**Comment by SavedByZero** [comment]
FWIw, I managed to accidentally fix it by removing my additional rigid body motions that these objects had in addition to my tweens. Somehow now upon scene reloading or upon other scenes playing before this one, the tweens continue to work…

**Comment by AliGhanitoos** [comment]
Hello, I had this problem and non of your solutions didn't help for me.
The problem was i didn't unsubscribe my event in OnDisable. It was a silly problem but easy to fix.
Hope you fix it :)

**Comment by joseribeiroejrs** [comment]
> Hi!
> 
> I see that you have your Unity's timeScale set to 0 ;) Unless your tweens are set to be timeScaleIndependent, Unity's timeScale will affect them.
> 
> Cheers, Daniele

You saved me! I was having this same problem lol

**Comment by RahulLinganagoudra** [comment]
I am having the problem with DoMove(), sometimes it used to work, sometimes it isn't, I was so confused and try to fix that for 3 days, I visited this page 5-6 times during the process. The problem was I was using CharacterController component, CharacterController blocks movement from Transform and rigidbody. The solution was simple, but I didn't know that, So I thought to share it.
