### ISSUE TITLE
Allow tweening for long and ulong data types

### ISSUE THREAD

**Issue by ScriptGeek** [Demigiant/dotween#6]
DOTween makes things incredibly easy and I'd like to see it support more of the primitive data types. My video game project requires unsigned long integers to tween a score display. It would be fantastic if DOTween provided a way to handle this.

**Comment by Demigiant** [comment]
Hi,

Not a problem at all, should take me just a short time. Gonna implement them in the next days.

**Comment by Demigiant** [comment]
Hey, I implemented it for _long_, but am having issues with _ulong_, and I'd need some help.

Obviously, I need to multiply a ulong for a float in order to tween it correctly. That is not a problem, and I end up with a float result that is the correct equivalent of the required ulong.

**The problem is between the conversion from _float_ to _ulong_.** Convert.ToUInt64 (as well as casting to _ulong_) returns a result, absurdly, whose max allowed value is the max value of a _long_ instead than of a _ulong_. The only thing that works is converting the resulting _float_ FIRST to a _string_ and THEN to a _ulong_. But the problem with that is that it generates byte allocations every frame because of the string.

Do you have any better idea for the conversion? Am I missing something?

**Comment by ScriptGeek** [comment]
Thanks for taking a look at this so quickly, I wasn't expecting such a lightning fast response!

I could probably buy some time by using the long data type in the meantime while ulong is being implemented.  I'll tinker around a bit and see what I can discover about conversions.  Maybe a persistent bit array can be used in the conversion process or maybe there's some other kind of built in conversion trick that will suffice.  I'll take a look and see what I can come up with.

**Comment by Demigiant** [comment]
Great, that would be very helpful.

In the meantime, you can grab the updated version [here](http://dotween.demigiant.com/tmp/DOTween_1_0_415.zip). Ulong is implemented too, just with those byte allocations that we don't like.

**Comment by ScriptGeek** [comment]
Well, I checked it out and I found a solution.  Cast the float to a decimal and then the decimal can be multiplied by the ulong.  So something like this:

ulong foo = (ulong)(ulong.MaxValue \* (decimal)1f;

**Comment by Demigiant** [comment]
Nice! Gonna try tomorrow morning :)

**Comment by Demigiant** [comment]
Works like a beauty, thanks a lot for the help! New download link coming in next comment

**Comment by Demigiant** [comment]
# Implemented in v1.0.416

[v1.0.416](http://dotween.demigiant.com/tmp/DOTween_1_0_416.zip)

**Comment by ScriptGeek** [comment]
Glad I could help, thanks for the awesome support!
