### ISSUE TITLE
Rotation issue with 1.1.135

### ISSUE THREAD

**Issue by yann-papouin** [Demigiant/dotween#60]
I have an issue with the use of DOLocalRotate. In some cases, I got wrong lerping, due to gimbal lock ? How can I fix this ?

**Please see video and project linked.**
http://ftpmerou.free.fr/dotween/rotation_issue.mp4 (5.7Mo)
http://ftpmerou.free.fr/dotween/Unity5.ProjetCarousel.zip (220Ko)

**Comment by Demigiant** [comment]
Hi Yann,

I'm not sure I can see any gimbal lock issues in your video. But there is a
special rotation method you can use in case that happens, instead of
DORotate: DORotateQuaternion
http://dotween.demigiant.com/documentation.php?api=DORotateQuaternion (which
uses straight quaternions instead of Vector3 for rotations, but has the
limit that it can't go beyond 180° rotations - because Quaternions don't
have it).

Let me know.

Cheers,
Daniele
