### ISSUE TITLE
About DOTWEEN OnComplete Function when i kill the Tweener

### ISSUE THREAD

**Issue by hyrio** [Demigiant/dotween#64]
Tweener  tweener = _cacheTransform.DOMove(new Vector3(SrcPos.x - posOffset, SrcPos.y, SrcPos.z), 0.15f);
tweener.SetLoops(-1, LoopType.Yoyo);
tweener.OnComplete(delegate()
{
      Debug.Log("testtttttt");
})

When I was at other places, kill the tweener like that:  tweener.Kill(false); or tweener.Kill(true);
the OnComplete Function not be called. Is this is a Bug?  
Now I have no way, i had to use OnSkill replace OnComplete. could you tell me how i can do it correct.
Thanks..

**Comment by Demigiant** [comment]
Hi,

Kill(true) does indeed complete a tween, but your case is special, because you have set infinite loops (-1). In that case, a tween can't really be completed, because it's infinite, so while Kill(true) will send the tween at the end of a loop step, the OnComplete callback will never fire. Write a very big integer for loops (like Int32.MaxValue) and the tween will be practically infinite, but the OnComplete event will be able to fire.

tweener.SetLoops(Int32.MaxValue, LoopType.Yoyo);

Cheers,
Daniele
