### ISSUE TITLE
[REQUEST] Auto Rewind Checkbox

### ISSUE THREAD

**Issue by lpendle** [Demigiant/dotween#65]
This would be nice to have when you want to repeat animations using Unity Event Triggers PointerEnter and PointerExit.

Thanks

Larry

**Comment by Demigiant** [comment]
Hi,

This is referred to DOTween Pro I suppose? In that case, you can use DOTweenAnimation's OnComplete to call the DORewind feature on the animation itself. I don't plan to add an auto-rewind, because that would actually require to actually use OnComplete in the background to do that, and it would get confusing because I would have to "lock it out".

P.S. To trigger a Restart (rewind + play) you can call DORestart.

Cheers,
Daniele
