### ISSUE TITLE
Tween not working - Scale

### ISSUE THREAD

**Issue by wrymn** [Demigiant/dotween#652]
I am not sure whether I am doing something wrong or this is actually not working, but I have super simple tween, and its just not scaling and animating at all.

![image](https://github.com/Demigiant/dotween/assets/12801017/0aa10b31-23e6-48fb-b840-a80f09b015c9)

This tween is just not playing at all when the object gets enabled.

**Comment by Demigiant** [comment]
Ahoy! Everything seems good there and I replicated your settings and it worked perfectly. Things that come to my mind:

1. Since the animation is set to start playing immediately but entering play mode in the Unity Editor causes Unity to hiccup for the first second or so (a known behaviour unrelated to DOTween but that happens only in the editor, Unity won't hiccup when starting builds), the animation plays but you don't have the time to see it. Does incresing the delay to 1.5 seconds show it?
2. The animation is set to AutoKill, so it will automatically be disposed of after it plays the first time. And if you're using i more times you won't see anything happen because of that (in that case just disable AutoKill)

**Comment by wrymn** [comment]
@Demigiant my bad, I did not notice the auto kill got enabled by default, yeah its working fine now :) Thank you for pointing this out.
