### ISSUE TITLE
Need more path movement support.

### ISSUE THREAD

**Issue by flywithfang** [Demigiant/dotween#7]
I am porting my tween to dotween from iTween.But I find a serious limitaton.
We need move by path like in iTween.
Now the DoPath always return to the origin position. It is useless in many cases.

So in DotTween, I  don't find any way to do path movement.
I think it is a serious limitation for a tween lib.
Please correct me if i am wrong.

Thank you.

**Comment by Demigiant** [comment]
Hi,

I'm not sure what you mean with "move by path like in iTween". A DOPath returns to the origin position only if the last waypoint coincides with that, if you use SetOptions to close the path, or if you set a Yoyo loop with even cycles. Those are all customized options, otherwise the path ends where the last waypoint is.

Also, as far as I know, DOTween (as HOTween before it) has more path movement features than iTween, so everything you did there you should be able to do here.

Let me know what you meant with more details.

Cheers,
Daniele

**Comment by Demigiant** [comment]
Heads up: didn't get any reply in 8 days, so unless I get one I'm gonna close this issue after 2 more days or so.

**Comment by Demigiant** [comment]
Closing this issue since I didn't receive any additional information

**Comment by flywithfang** [comment]
sorry for the late reply. i am busy these days.
DoPath is ok. It work as I wish and no loop.
I recheck my original code.
I use one gaussian curve as the ease cure  in the following code, so the cube will return to the path origin.
It is my fault.
Now we are using Dotween happily. Thank you for your great software.
Sequence mySequence = DOTween.Sequence();

```
    var dir = new Vector3(1f,0f,1f).normalized;
    Vector3[] ps= new Vector3[2];

    ps[0]=target.position + dir*3f ;
    ps[0].y+= 3f;
    ps[1] = target.position + dir*6f;

    mySequence.Append(target.DOPath(ps,1f,PathType.CatmullRom).SetEase(curve).SetOptions(false).SetLoops(0));
```

**Comment by Demigiant** [comment]
Thank you for the update, and glad all it's working :)
