### ISSUE TITLE
Cannot implicitly convert type `LoopType' to `DG.Tweening.LoopType'.

### ISSUE THREAD

**Issue by ctc53** [Demigiant/dotween#80]
Assets/Demigiant/DOTweenPro/Editor/DOTweenAnimationInspector.cs(325,22): error CS0266: Cannot implicitly convert type `LoopType' to`DG.Tweening.LoopType'. An explicit conversion exists (are you missing a cast?)

Unity version: 5.4.0b24

**Comment by Demigiant** [comment]
Hi,

This means you have some other asset (or your code) that has a class/enum called LoopType, and is wrongly not inside a namespace. This is a bug in the other asset/code, since that means that it won't allow any other LoopType objects to co-exist with it. If you find the culprit please let me know: in case it's an asset I can write to the author and ask him to use namespaces.

P.S. to fix it, just find the other class and place its LoopType object inside a namespace.

Cheers,
Daniele
