### ISSUE TITLE
Loop inside sequence seems to run just one time

### ISSUE THREAD

**Issue by kruncher** [Demigiant/dotween#92]
In the documentation it says that loops inside sequences get set to one iteration rather than being endless.

I have added workarounds in my current project; but what would be wrong with allowing endless loops inside sequences? Is this a feature that could be added at some point?

**Use Case 1 - A sequence that has a one-off intro with a looped sequence at the end:**

``` csharp
this.tween = DOTween.Sequence()
    .Append(
        modelTransform
            .DOLocalRotateQuaternion(minRotation, 0.5f)
            .SetEase(Ease.InOutSine)
    )
    .Append(
        modelTransform
            .DOLocalRotateQuaternion(this.Context.IdleRotationOffset, 0.5f)
            .SetEase(Ease.InOutSine)
            .SetLoops(-1, LoopType.Yoyo);
    );
```

Here is how I am currently handling this situation; not massively different syntax-wise; but the use of the delegate here causes a small allocation which could be avoided if the endless loop was supported with the above syntax.

``` csharp
this.tween = DOTween.Sequence()
    .Append(
        modelTransform
            .DOLocalRotateQuaternion(minRotation, 0.5f)
            .SetEase(Ease.InOutSine)
    )
    .AppendCallback(() => {
        // The most annoying thing with this syntax is that the tween reference
        // must be updated so that the sequence can be killed easily.
        this.tween = modelTransform
            .DOLocalRotateQuaternion(this.Context.IdleRotationOffset, 0.5f)
            .SetEase(Ease.InOutSine)
            .SetLoops(-1, LoopType.Yoyo);
    });
```

**Use Case 2 - An inner loop that terminates after some condition**

``` csharp
this.tween = DOTween.Sequence()
    .Append(
        this.innerLoopTween = modelTransform
            .DOLocalRotateQuaternion(this.Context.IdleRotationOffset, 0.5f)
            .SetEase(Ease.InOutSine)
            .SetLoops(-1, LoopType.Yoyo);
    )
    .Append(
        modelTransform
            .DOLocalRotateQuaternion(minRotation, 0.5f)
            .SetEase(Ease.InOutSine)
    );

// Elsewhere; break inner loop and allow outer sequence to continue.
this.innerLoopTween.Kill(complete = true);
```

Many thanks :)

**Comment by Demigiant** [comment]
Ahoy! :)

There's a misunderstanding of how Sequences work here. They are like a fixed videoclip of tweens, not like a dynamic one. Meaning you can't act on inner tweens after they've been added to a Sequence (so you wouldn't be able to terminate a nested tween loop like in your Use Case 2: you can only act on the Sequence itself), and that the Sequence itself, in order to work correctly, needs to know its total duration (Sequence loops excluded). That's the main reason why infinite nested loops aren't allowed. Still, unless you're working on a kiosk application that might run for days, you could always set the total loops to Int32.MaxValue, which would make the loops be "almost" infinite.

Cheers :)
Daniele
